### ISSUE TITLE
Unhandled Exception: error accessing property

### ISSUE THREAD

**Issue by bytecntrl** [ryanheise/just_audio#1014]
**Which API doesn't behave as documented, and how does it misbehave?**
I'm encountering an error while calling setAudioSource audio player method.
I'm only using a local audio files.
I'm on arch linux, I've tried this on macOS and this works. 

**Minimal reproduction project**
```
play() async {
    AudioPlayer audioPlayer = AudioPlayer();

    final ConcatenatingAudioSource _playlist = ConcatenatingAudioSource(
      useLazyPreparation: true,
      shuffleOrder: DefaultShuffleOrder(),
      children: [],
    );

    if (soundTracks.isEmpty) {
      return;
    }

    for (final elem in soundTracks) {
      _playlist.add(AudioSource.uri(Uri.parse("file://${elem.path}")));
    }

    await audioPlayer.setAudioSource(_playlist,
        initialIndex: 0, initialPosition: Duration.zero);
    await audioPlayer.setLoopMode(LoopMode.all);
    await audioPlayer.setShuffleModeEnabled(true);
   await audioPlayer.play();
  }
```

**Error messages**
```
flutter: MPV 1c72f77b-d3f7-4afa-9848-0dbb1977930a started
flutter: MPV 1c72f77b-d3f7-4afa-9848-0dbb1977930a loading track...
flutter: {type: concatenating, id: 95f87c48-f18b-4258-b8c8-db8e34500764, children: [{type: progressive, id: 6d964a96-af52-43ea-b240-8ddb2ded6219, uri: file:///home/francesco/Documenti/file_example_MP3_700KB.mp3, headers: null}, {type: progressive, id: 1938b472-356a-4fd0-a4e7-e67bcf236359, uri: file:///home/francesco/Documenti/edit_21.mp3, headers: null}, {type: progressive, id: cb636374-f214-4982-8f44-764623b5f6fc, uri: file:///home/francesco/Documenti/edit_10.mp3, headers: null}, {type: progressive, id: 7bbb83bc-42f8-4d95-8854-d87467934ea6, uri: file:///home/francesco/Documenti/edit_7.mp3, headers: null}, {type: progressive, id: d578cca5-28b6-40e2-b4fa-69ef7e3f2a51, uri: file:///home/francesco/Documenti/edit_3.mp3, headers: null}], useLazyPreparation: true, shuffleOrder: [0, 1, 2, 3, 4]}
flutter: MPV 1c72f77b-d3f7-4afa-9848-0dbb1977930a quitting at request
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Cannot add new events after calling close
#0      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:243:24)
#1      JustAudioMPVPlayer.update (package:just_audio_mpv/src/mpv_player.dart:30:24)
<asynchronous suspension>
#2      new JustAudioMPVPlayer.<anonymous closure> (package:just_audio_mpv/src/mpv_player.dart:61:7)
<asynchronous suspension>

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Cannot add new events after calling close
#0      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:243:24)
#1      JustAudioMPVPlayer.update (package:just_audio_mpv/src/mpv_player.dart:30:24)
<asynchronous suspension>
#2      new JustAudioMPVPlayer.<anonymous closure> (package:just_audio_mpv/src/mpv_player.dart:61:7)
<asynchronous suspension>

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Cannot add new events after calling close
#0      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:243:24)
#1      JustAudioMPVPlayer.update (package:just_audio_mpv/src/mpv_player.dart:30:24)
<asynchronous suspension>
#2      new JustAudioMPVPlayer.<anonymous closure> (package:just_audio_mpv/src/mpv_player.dart:61:7)
<asynchronous suspension>

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Cannot add new events after calling close
#0      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:243:24)
#1      JustAudioMPVPlayer.update (package:just_audio_mpv/src/mpv_player.dart:30:24)
<asynchronous suspension>
#2      new JustAudioMPVPlayer.<anonymous closure> (package:just_audio_mpv/src/mpv_player.dart:61:7)
<asynchronous suspension>

flutter: MPV 1c72f77b-d3f7-4afa-9848-0dbb1977930a exited
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: error accessing property
```

**Expected behavior**
The audio player should play.

**Desktop (please complete the following information):**
 - OS: Arch linux

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.5, on Arch Linux 6.3.9-arch1-1, locale it_IT.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.1)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

**Comment by zsakvo** [comment]
Ubuntu22.04, got same error.

**Comment by ryanheise** [comment]
If you are using the mpv implementation, I would suggest opening an issue here:

https://github.com/bleonard252/just_audio_mpv

**Comment by bytecntrl** [comment]
thanks, I'll close here and open in the other repo
