### ISSUE TITLE
issingPluginException(No implementation found for method init on channel com.ryanheise.just_audio.methods)

### ISSUE THREAD

**Issue by dangmt-se** [ryanheise/just_audio#1026]
**Which API doesn't behave as documented, and how does it misbehave?**
Name here the specific methods or fields that are not behaving as documented, and explain clearly what is happening.

I implemented the plug-in in Flutter Web and it's working like a charm on my local host.
But when I test run the project on my generated github.io site, the music app does not play. 

**Minimal reproduction project**
Provide a link here using one of two options:
2. "The example".]

**To Reproduce (i.e. user steps, not code)**

**Error messages**

```
Uncaught MissingPluginException(No implementation found for method init on channel com.ryanheise.just_audio.methods)
at Object.f (https://cretaisland.github.io/creta03_v3/main.dart.js:4445:3)
at https://cretaisland.github.io/creta03_v3/main.dart.js:144060:15
at c6w.a (https://cretaisland.github.io/creta03_v3/main.dart.js:5762:62)
at c6w.$2 (https://cretaisland.github.io/creta03_v3/main.dart.js:67043:14)
at c3H.$1 (https://cretaisland.github.io/creta03_v3/main.dart.js:67037:21)
at aDn.adc (https://cretaisland.github.io/creta03_v3/main.dart.js:68066:34)
at bPe.$0 (https://cretaisland.github.io/creta03_v3/main.dart.js:67453:11)
at Object.RV (https://cretaisland.github.io/creta03_v3/main.dart.js:5899:40)
at aM.x7 (https://cretaisland.github.io/creta03_v3/main.dart.js:67374:3)
at bP6.$0 (https://cretaisland.github.io/creta03_v3/main.dart.js:67420:13)
```

**Expected behavior**
The app can play music on the .github.io site

**Desktop (please complete the following information):**
 - Working on local host on Chrome but not on the .github.io site. 

**Flutter SDK version**
```
[✓] Flutter (Channel stable, 3.10.6, on Microsoft Windows [Version 10.0.22621.1992], locale en-US)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✗] Android toolchain - develop for Android devices
    ✗ ANDROID_HOME = C:\dev\sdk
      but Android SDK not found at this location.
[✓] Chrome - develop for the web
[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.4)
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.80.1)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

**Comment by ryanheise** [comment]
Just to confirm, this error was produced using the official example, according to the reproduction instructions above?

**Comment by dangmt-se** [comment]
Yes,, it was. 
Running on local is fine but it seems like the plug-in has problem with the github host?

**Comment by ryanheise** [comment]
Can you please paste the error message in plain text within a code block?

Edit: and also, edit your existing bug report to use this format.

**Comment by dangmt-se** [comment]
Is it what you meant?

Uncaught MissingPluginException(No implementation found for method init on channel com.ryanheise.just_audio.methods)
  at Object.f (https://cretaisland.github.io/creta03_v3/main.dart.js:4445:3)
    at https://cretaisland.github.io/creta03_v3/main.dart.js:144060:15
    at c6w.a (https://cretaisland.github.io/creta03_v3/main.dart.js:5762:62)
    at c6w.$2 (https://cretaisland.github.io/creta03_v3/main.dart.js:67043:14)
    at c3H.$1 (https://cretaisland.github.io/creta03_v3/main.dart.js:67037:21)
    at aDn.adc (https://cretaisland.github.io/creta03_v3/main.dart.js:68066:34)
    at bPe.$0 (https://cretaisland.github.io/creta03_v3/main.dart.js:67453:11)
    at Object.RV (https://cretaisland.github.io/creta03_v3/main.dart.js:5899:40)
    at aM.x7 (https://cretaisland.github.io/creta03_v3/main.dart.js:67374:3)
    at bP6.$0 (https://cretaisland.github.io/creta03_v3/main.dart.js:67420:13)

**Comment by ryanheise** [comment]
That's not in a code block. The original bug report template included a code block and you just needed to insert the error message between the start and end of that code block. Maybe you ignored it and deleted it. Here is an example:

```
This is a code block
```

Use a fence above and below (a row of 3 back ticks). And edit your original report rather than adding more comments below.

**Comment by dangmt-se** [comment]
Thank you! I put the error message within the 3 back ticks now. 

```
Uncaught MissingPluginException(No implementation found for method init on channel com.ryanheise.just_audio.methods)
at Object.f (https://cretaisland.github.io/creta03_v3/main.dart.js:4445:3)
at https://cretaisland.github.io/creta03_v3/main.dart.js:144060:15
at c6w.a (https://cretaisland.github.io/creta03_v3/main.dart.js:5762:62)
at c6w.$2 (https://cretaisland.github.io/creta03_v3/main.dart.js:67043:14)
at c3H.$1 (https://cretaisland.github.io/creta03_v3/main.dart.js:67037:21)
at aDn.adc (https://cretaisland.github.io/creta03_v3/main.dart.js:68066:34)
at bPe.$0 (https://cretaisland.github.io/creta03_v3/main.dart.js:67453:11)
at Object.RV (https://cretaisland.github.io/creta03_v3/main.dart.js:5899:40)
at aM.x7 (https://cretaisland.github.io/creta03_v3/main.dart.js:67374:3)
at bP6.$0 (https://cretaisland.github.io/creta03_v3/main.dart.js:67420:13)
```

**Comment by ryanheise** [comment]
You didn't edit your original report. The screenshot is still there.

**Comment by dangmt-se** [comment]
I edited my original report. Please check, thank you!

**Comment by ryanheise** [comment]
Do you have a link to the github.io site?

**Comment by dangmt-se** [comment]
I do... but it is used only within the company only. Sorry I couldn't provide it due to confidential issue :(

**Comment by ryanheise** [comment]
It's my code we're talking about here, since you said this is the official example.

**Comment by dangmt-se** [comment]
Your code is working fine on the local host and having trouble on the gihub.io platform. Just thought there're something to do with the plug-in permission or dependencies... Sorry again, I can't provide more details on the github.io site.

**Comment by ryanheise** [comment]
So is the problem with github.io specifically? Or can you verify that it is a problem with just_audio_web (e.g. by showing that it also fails in the same way on a regular web server)?

**Comment by dangmt-se** [comment]
That's right. The problem is with github.io specifically. It works well on the localhost chrome.

**Comment by ryanheise** [comment]
I don't mean localhost, I mean a regular web server. If you are able to install apache or nginx locally, you may test that to verify if those work.

**Comment by dangmt-se** [comment]
Thank you! I will test on those and get back to you!

**Comment by dangmt-se** [comment]
Hi, I test the web application on nginx and the plug-ins work fine there too. 
So it means that the problem is only with gihub.io then.

**Comment by B0yma** [comment]
Have the same issue - on firebase hosting


> Thank you! I put the error message within the 3 back ticks now.
> 
> ```
> Uncaught MissingPluginException(No implementation found for method init on channel com.ryanheise.just_audio.methods)
> at Object.f (https://cretaisland.github.io/creta03_v3/main.dart.js:4445:3)
> at https://cretaisland.github.io/creta03_v3/main.dart.js:144060:15
> at c6w.a (https://cretaisland.github.io/creta03_v3/main.dart.js:5762:62)
> at c6w.$2 (https://cretaisland.github.io/creta03_v3/main.dart.js:67043:14)
> at c3H.$1 (https://cretaisland.github.io/creta03_v3/main.dart.js:67037:21)
> at aDn.adc (https://cretaisland.github.io/creta03_v3/main.dart.js:68066:34)
> at bPe.$0 (https://cretaisland.github.io/creta03_v3/main.dart.js:67453:11)
> at Object.RV (https://cretaisland.github.io/creta03_v3/main.dart.js:5899:40)
> at aM.x7 (https://cretaisland.github.io/creta03_v3/main.dart.js:67374:3)
> at bP6.$0 (https://cretaisland.github.io/creta03_v3/main.dart.js:67420:13)
> ```

^^^

> Do you have a link to the github.io site?

**Comment by B0yma** [comment]
so my solution:

in your main.dart need to manually register plugin for web:
```dart
...
import 'package:flutter_web_plugins/flutter_web_plugins.dart';
...

*YOUR PLUGIN*.registerWith(webPluginRegistrar);

```

**Comment by tarunsachdeva001** [comment]
@B0yma  Can you please more details of how you resolve this issue. I am also facing same issue that audio is not working after deploy on firebase. 

*YOUR PLUGIN*.registerWith(webPluginRegistrar);  //Can you complete this line w.r.t plugin.

it will be really helpful. 

Thank you

**Comment by B0yma** [comment]
> @B0yma Can you please more details of how you resolve this issue. I am also facing same issue that audio is not working after deploy on firebase.
> 
> _YOUR PLUGIN_.registerWith(webPluginRegistrar); //Can you complete this line w.r.t plugin.
> 
> it will be really helpful.
> 
> Thank you

@tarunsachdeva001 Hello, actually you dont this but if nothing work for the case with this - JustAudioPlugin.registerWith(registrar);
So the core problem is in the cache, try to run command - flutter upgrade - then try to delete in your project folder, folders: .dart_tool, .firebase

**Comment by akastha97** [comment]
Hi,  I am getting the same exception but on an iOS simulator (iphone 15 pro max).  I tried to open new issue but github bot closes it up because of missing format.  
This is my code:
```**Future playSampleAudio() async { try { const file = 'assets/audio/sample.mp3'; await _audioPlayer.setSourceAsset(file); await _audioPlayer.play(); } catch (e) { print("Error playing audio file $e"); } }**```

```
✓] Flutter (Channel stable, 3.22.0, on macOS 14.3 23D56 darwin-arm64, locale en-US)
    • Flutter version 3.22.0 on channel stable at /Users/ash/Documents/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5dcb86f68f (10 weeks ago), 2024-05-09 07:39:20 -0500
    • Engine revision f6344b75dc
    • Dart version 3.4.0
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/ash/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2
```

I have tried audioplayers latest version first, which showed up DarwinError, and then switched to just_audio. I have looked at the MissingPluginException bug that was closed but couldnt figure out the solution. Lot of people mentioned that removing facebook login package fixed the issue, but i'm not even using that package. And the issue is on my ios simulator. Can someone point me out in the right direction? Thanks in advance.

These are my dependencies:
logger: ^2.3.0 stacked: ^3.4.2 stacked_services: ^1.5.0 firebase_auth: ^5.1.1 firebase_core: ^3.1.1 firebase_crashlytics: ^4.0.2 firebase_storage: ^12.1.0 flutter_svg: ^2.0.7 google_sign_in: ^6.2.1 sentry_flutter: ^8.3.0 permission_handler: ^11.3.1 percent_indicator: ^4.2.3 loading_indicator: ^3.1.1 semicircle_indicator: ^1.1.1 fl_chart: ^0.68.0 dart_mappable: ^4.0.0 remaths: ^0.0.7 connectivity_plus: ^6.0.3 custom_date_range_picker: ^1.1.0 cloud_firestore: ^5.0.2 cloud_functions: ^5.0.2 carousel_slider: ^4.2.1 just_audio: ^0.9.39

**Comment by ryanheise** [comment]
> Hi, I am getting the same exception but on an iOS simulator

@akastha97 This issue is a particular issue concerning web. Your issue is different as it relates to iOS. Please open a new bug report specific to your issue. I'll close this comment as off topic. (Yes, I have seen you post 3 new issues already, all 3 of which ignored the instructions. Please don't do that as it creates a hassle for me.)
