### ISSUE TITLE
Set User-Agent customization 

### ISSUE THREAD

**Issue by getmmg** [ryanheise/just_audio#105]
**Is your feature request related to a problem? Please describe.**

Currently the user-agent is set to just_audio and version, I have a requirement that it needs a custom header. 

**Describe the solution you'd like**
Set the UserAgent in AudioPlayer Constructor or an optional argument in setUrl

**Comment by naguchennai** [comment]
This is only audio service code.. If you want change user agent or customization  you must ask [Just_audio ](https://pub.dev/packages/just_audio#-readme-tab-).. They only playing audio ... thank you

**Comment by naguchennai** [comment]
Yes i also want it thank you

**Comment by ryanheise** [comment]
I have implemented a proxy-based solution in the latest commit. There are still unresolved issues with the the `position<=duration` constraint being violated, although this is regarding a separate PR and I'm working on a fix for that.

Note that the proxy-based solution I implemented does not yet recursively apply headers to items in playlist formats like `m3u8` but it should work for simple URLs like `.mp3`. The solution should also work for Android, iOS, macOS, but not web (a separate solution will be needed for this platform).

**Comment by ryanheise** [comment]
The unrelated issue with the duration is now resolved.

Let me know if the headers parameter works for you, or whether you need this to work for playlist formats like `m3u8`.

**Comment by getmmg** [comment]
Hi I am setting Header like below 

`Map<String,String> header = {'user-agent' : 'xxx'}`

In the request I am seeing the header as `user-agent: Dart/2.8 (dart:io), xxx`, Is it possible to remove the extra and keep only the xxx as user-agent.

**Comment by ryanheise** [comment]
Ah, interesting. Yes I can take a look at that tomorrow.

**Comment by ryanheise** [comment]
This should be fixed in the latest commit.

**Comment by ryanheise** [comment]
This is now available in the 0.2.0 release.

**Comment by getmmg** [comment]
Hi @ryanheise 

I have noticed couple of issues with 0.2.0 

Getting below exception while trying to play some url's 

```
E/flutter (15845): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: HttpException: Invalid response line, uri = http://103.16.47.70:9555/;stream.mp3
E/flutter (15845): #0      _HttpParser._doParse (dart:_http/http_parser.dart:459:15)
E/flutter (15845): #1      _HttpParser._parse (dart:_http/http_parser.dart:328:7)
E/flutter (15845): #2      _HttpParser._onData (dart:_http/http_parser.dart:850:5)
E/flutter (15845): #3      _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter (15845): #4      _CustomZone.runUnary (dart:async/zone.dart:1085:19)

```

Also noticed that **IcyMetaData** is not updating anymore.

**Comment by getmmg** [comment]
I mean whenever I set the custom header in setUrl call IcyMetaData will stop updating.

**Comment by ryanheise** [comment]
Hi @getmmg 

Regarding the Icy Metadata, to help me test, can you try including the following header in your request?

```dart
{ 'Icy-MetaData': '1' }
```

**Comment by getmmg** [comment]
Hi @ryanheise, 

I did set it, I didn't see any change. What should I be looking?

**Comment by ryanheise** [comment]
Hi @getmmg 

I have hopefully fixed the missing icy headers issue in the latest commit. You should not need to pass the icy header manually now, that will be done by the plugin, so you can try just sending your user agent.

I am not sure about the other error though (the parse error) since I wasn't able to reproduce it.

Let me know how it goes.

**Comment by getmmg** [comment]
Hi @ryanheise, 
Yes IcyHeaders are working now Thanks. 

This is running fine 

`audioPlayer.setUrl('http://109.169.23.22:28976/')`

and this is the user-agent added by android exoplayer   **User-Agent: just_audio/1.0.15 (Linux;Android 7.1.2) ExoPlayerLib/2.11.4**

When I run the same with the Proxy Server and set the same useragent its failing giving the error

`audioPlayer.setUrl('http://109.169.23.22:28976/','User-Agent': 'just_audio/1.0.15 (Linux;Android 7.1.2) ExoPlayerLib/2.11.4')`

First call don't produce whereas the second one produce error. 




To Reproduce parse error you can try this url 
http://103.16.47.70:9555/;stream.mp3

**Comment by ryanheise** [comment]
Thanks for these test cases, it will be really useful. It is getting quite late here (3:45am!), so I will look into this tomorrow.

**Comment by ryanheise** [comment]
The reason for the parse error is because `http://109.169.23.22:28976/` is giving a HTTP/0.9 response which is unfortunately not supported by The Dart HTTP libraries.

I can implement a solution that will work for Android only if that will address your immediate needs.

In terms of iOS, there are several options from easiest to hardest:

* Use an undocumented iOS API that may risk your app getting rejected by the Apple Store (although I'd prefer to avoid this)
* Submit a feature request to the Dart team to add HTTP 0.9 support.
* Submit a PR to the Dart team.
* Implement the proxy using sockets.

Another stream on the same server works since it uses HTTP 1.0 (http://109.169.23.22:36263/1). Do you know if there is any way to request the version of HTTP that your stream uses?

**Comment by getmmg** [comment]
Hi @ryanheise,

Android only solution is fine, since I am not building anything for ios at least for now.
Http 1.0 stream you mentioned is a different different stream which I am not interested.

**Comment by ryanheise** [comment]
Being a little crazy, I decided on implementing what I thought was the hardest option :-) It turned out to be easier than expected because Dart's HTTP API allows me to detach the socket and implement and handle this exceptional case.

Anyway, I've committed this latest change. Let me know if it works for you.
