### ISSUE TITLE
Range request supported URL is not working cached play in iOS

### ISSUE THREAD

**Issue by dejay-dev** [ryanheise/just_audio#1065]
**Which API doesn't behave as documented, and how does it misbehave?**
Range request supported URL is not playing by cached LockCachingAudioSource in iOS.
Same URL is working well in Android.

**Minimal reproduction project**
Change URL to "https://resource.sleepwave.ai/v1/sound/sound/0101004.mp3"
in example_caching.dart from official example

**To Reproduce (i.e. user steps, not code)**
Touch Play button and you can see below error messages

**Error messages**
```
flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: (-11828) can not open
flutter: 
#0      AudioPlayer._load (package:just_audio/just_audio.dart:851:9)
<asynchronous suspension>
#1      AudioPlayer._setPlatformActive.setPlatform (package:just_audio/just_audio.dart:1436:28)
<asynchronous suspension>
flutter: ----------------------------------------------------
```

**Expected behavior**
It has to be play sound well with caching.

**Smartphone (please complete the following information):**
 - Device: iPhone 8+
 - OS: iOS 16.0.2

**Flutter SDK version**
```
[✓] Flutter (Channel stable, 3.13.4, on macOS 13.3.1 22E772610a darwin-x64, locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google
    Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2021.3)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

**Comment by func25** [comment]
This solution worked for me: change the `Content-Type` response to `audio/mpeg`, for files with a .wav extension, use `audio/wav`.

**Comment by danielgomezrico** [comment]
@func25 where? can you show an example?
