### ISSUE TITLE
java.lang.NullPointerException Attempt to invoke interface method 'boolean a3.x.m()' on a null object reference

### ISSUE THREAD

**Issue by mysticeti** [ryanheise/just_audio#1126]
**Which API doesn't behave as documented, and how does it misbehave?**
I believe dispose method for players. I am getting the crash on a user and the log from crashlytics is given below

Not sure but the code gets crashed in setMediaSource from this PR [https://github.com/ryanheise/just_audio/pull/310](https://github.com/ryanheise/just_audio/pull/310)

**Minimal reproduction project**
I believe any project where the app is being disposed.

**To Reproduce (i.e. user steps, not code)**
1. Open any flutter app with audioplayer
2. Put the app in background
3. After awhile depends on when os tries to close the app permanently
4. crash occurs for some devices

**Error messages**

```
Fatal Exception: java.lang.RuntimeException: Unable to destroy activity {com.example.app/com.example.app.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'boolean a3.x.m()' on a null object reference
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5158)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5187)
       at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2116)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7723)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)

Caused by java.lang.NullPointerException: Attempt to invoke interface method 'boolean a3.x.m()' on a null object reference
       at com.google.android.exoplayer2.source.MaskingMediaSource.<init>(MaskingMediaSource.java:6)
       at com.google.android.exoplayer2.MediaSourceList$MediaSourceHolder.<init>(MediaSourceList.java:5)
       at com.google.android.exoplayer2.ExoPlayerImpl.addMediaSourceHolders(ExoPlayerImpl.java:22)
       at com.google.android.exoplayer2.ExoPlayerImpl.setMediaSourcesInternal(ExoPlayerImpl.java:38)
       at com.google.android.exoplayer2.ExoPlayerImpl.setMediaSources(ExoPlayerImpl.java:12)
       at com.google.android.exoplayer2.ExoPlayerImpl.setMediaSources(ExoPlayerImpl.java:4)
       at com.google.android.exoplayer2.ExoPlayerImpl.setMediaSource(ExoPlayerImpl.java:7)
       at com.ryanheise.just_audio.AudioPlayer.onPlayerError(AudioPlayer.java:167)
       at com.google.android.exoplayer2.ExoPlayerImpl.lambda$release$5(ExoPlayerImpl.java:12)
       at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:17)
       at com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:16)
       at com.google.android.exoplayer2.util.ListenerSet.flushEvents(ListenerSet.java:69)
       at com.google.android.exoplayer2.util.ListenerSet.sendEvent(ListenerSet.java:3)
       at com.google.android.exoplayer2.ExoPlayerImpl.release(ExoPlayerImpl.java:127)
       at com.ryanheise.just_audio.AudioPlayer.dispose(AudioPlayer.java:38)
       at com.ryanheise.just_audio.MainMethodCallHandler.dispose(MainMethodCallHandler.java:27)
       at com.ryanheise.just_audio.JustAudioPlugin.onDetachedFromEngine(JustAudioPlugin.java:2)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:121)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:16)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.removeAll(FlutterEngineConnectionRegistry.java:11)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.destroy(FlutterEngineConnectionRegistry.java:10)
       at io.flutter.embedding.engine.FlutterEngine.destroy(FlutterEngine.java:31)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:100)
       at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:18)
       at android.app.Activity.performDestroy(Activity.java:8245)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1344)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5143)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5187)
       at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2116)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7723)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
```

**Expected behavior**
The player should dispose without any crash

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS + version]
 - Browser [e.g. chrome, safari + version]

**Smartphone (please complete the following information):**
 - Device: Walton - FIH Foxconn
 - OS: Android 11

**Flutter SDK version**
```
3.13.9
```

**Additional context**
In main.dart
```
@override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
    _log.info('Subscribed to app lifecycle updates');

  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    super.didChangeAppLifecycleState(state);
    _log.info('didChangeAppLifecycleState: $state');

    if (state == AppLifecycleState.resumed) {
      playAmbientMusicWithCheck(
          gameSettingsState: ref
              .read(gameSettingsProvider)
              .value,
          audioController: ref.read(soundControllerProvider));
    } else {
      ref.read(soundControllerProvider).pauseAmbientMusic();
    }
  }

  @override
  void dispose() {
    _log.info(() => 'main.dart dispose');

    WidgetsBinding.instance.removeObserver(this);
    ref.read(soundControllerProvider.notifier).dispose();

    super.dispose();
  }
```

AudioController.dart
```
class AudioController {
  static final _log = Logger('AudioController');
  final Ref ref;

  final AudioPlayer _musicPlayer;

  bool audioInitComplete = false;

  /// This is a list of [AudioPlayer] instances which are rotated to play
  /// sound effects.
  final List<AudioPlayer> _sfxPlayers;

  final ConcatenatingAudioSource _ambientMusicPlaylist;

  AudioController(
    this.ref, {
    int polyphony = 3,
  })  : assert(polyphony >= 1),
        _musicPlayer = AudioPlayer(),
        _sfxPlayers = Iterable.generate(polyphony, (i) => AudioPlayer())
            .toList(growable: false),
        _ambientMusicPlaylist = ConcatenatingAudioSource(
          // Start loading next item just before reaching it
          useLazyPreparation: true,
          // Customise the shuffle algorithm
          shuffleOrder: DefaultShuffleOrder(),
          // Specify the playlist items
          children: songs.map((song) {
            return AudioSource.asset('assets/music/${song.filename}');
          }).toList(growable: false),
        );

  /// Init method with [sfxVolume] and [ambientMusicVolume] being between 0.0 and 1.0
  Future<void> init(double sfxVolume, double ambientMusicVolume) async {
    if (!audioInitComplete) {
      _log.info("AudioController initialising");
      try {
        await _musicPlayer.setAudioSource(_ambientMusicPlaylist,
            preload: false, initialIndex: 0, initialPosition: Duration.zero);

        // preload sfx
        for (int i = 0; i < SfxType.values.length; i++) {
          final options = soundTypeToFilename(SfxType.values[i]);
          final filename = options[0];
          await _sfxPlayers[i].setAsset('assets/sfx/$filename');
        }
      } catch (e) {
        debugPrint("Error setting audio source for music player");
      }

      await _musicPlayer.setVolume(ambientMusicVolume);
      await _musicPlayer.setLoopMode(LoopMode.all);

      for (final player in _sfxPlayers) {
        await player.setVolume(sfxVolume);
      }
      audioInitComplete = true;
    }
  }

  void dispose() {
    stopAllSound();
    _musicPlayer.dispose();
    for (final player in _sfxPlayers) {
      player.dispose();
    }
  }

  Future<void> updateSFXVolume(double newSFXVolume) async {
    for (final player in _sfxPlayers) {
      await player.setVolume(newSFXVolume);
      _log.info('Setting sfx volume');
    }
  }

  Future<void> updateMusicVolume(double newMusicVolume) async {
    _log.info('Setting ambient music volume');
    _musicPlayer.setVolume(newMusicVolume);
  }

  Future<void> pauseAmbientMusic() async {
    _log.info('Pausing ambient music');
    if (_musicPlayer.playing) {
      await _musicPlayer.pause();
      _log.info('Paused ambient music');
    }
  }

  Future<void> playSFX(SfxType type) async {
    _log.info(() => 'Playing sound: $type');

    switch (type) {
      case SfxType.correct:
        _sfxPlayers[0].seek(Duration.zero);
        _sfxPlayers[0].play();
        break;
      case SfxType.wrong:
        _sfxPlayers[1].seek(Duration.zero);
        _sfxPlayers[1].play();
        break;
      case SfxType.neutral:
        _sfxPlayers[2].seek(Duration.zero);
        _sfxPlayers[2].play();
        break;
    }
  }

  Future<void> startAmbientMusic() async {
    _log.info('Starting ambient music');
    if (_musicPlayer.playing == false) {
      await _musicPlayer.play();
      _log.info('Started ambient music');
    }
  }

  Future<void> stopAllSFX() async {
    _log.info('Stopping all sfx');
    for (final player in _sfxPlayers) {
      await player.stop();
    }
  }

  Future<void> stopAllSound() async {
    _log.info('Stopping all sound');
    stopAmbientMusic();
    stopAllSFX();
  }

  Future<void> stopAmbientMusic() async {
    _log.info('Stopping ambient music');

    if (_musicPlayer.playing) {
      await _musicPlayer.stop();
    }
  }
}
```

Riverpod pod SoundController.dart
```
@Riverpod(keepAlive: true)
class SoundController extends _$SoundController {
  @override
  AudioController build() {
    return AudioController(ref);
  }

  void dispose() {
    state.dispose();
  }
}
```

**Comment by ryanheise** [comment]
As was explained to you in your previous issue:

> This is frowned upon, and the issue will be closed manually.

As such, I will manually close this issue. Please don't ignore the instructions as it only wastes people's time.
