### ISSUE TITLE
why await do not work?

### ISSUE THREAD

**Issue by sunjianan9900** [ryanheise/just_audio#133]
**Flutter web**

```
final duration = await player.setUrl('http://127.0.0.1:8000/a.mp3');
print("1 == ${duration}");
await new Future.delayed(new Duration(milliseconds: 3000));
print("2 == ${duration}");
player.play();
```
works well and print ->

```
1 == 0:00:03.528000
2 == 0:00:03.528000
```

BUT
```
final duration = await player.setUrl('http://127.0.0.1:8000/a.mp3');
print("1 == ${duration}");
// await new Future.delayed(new Duration(milliseconds: 3000));
print("2 == ${duration}");
player.play();
```

not work and print

```
1 == 0:00:03.528000
2 == 0:00:03.528000
Error: Exception: Cannot call play from connecting/none states (AudioPlaybackState.connecting)
    at Object.throw_ [as throw] (http://localhost:56054/dart_sdk.js:4330:11)
    at just_audio.AudioPlayer._internal.play (http://localhost:56054/packages/just_audio/just_audio.dart.lib.js:355:23)
    at play.next (<anonymous>)
    at runBody (http://localhost:56054/dart_sdk.js:37387:34)
    at Object._async [as async] (http://localhost:56054/dart_sdk.js:37418:7)
    at just_audio.AudioPlayer._internal.play (http://localhost:56054/packages/just_audio/just_audio.dart.lib.js:330:20)
    at http://localhost:56054/packages/subspeaker/mwidget/task_submit.dart.lib.js:4413:26
    at Generator.next (<anonymous>)
    at http://localhost:56054/dart_sdk.js:37367:33
    at _RootZone.runUnary (http://localhost:56054/dart_sdk.js:37221:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:56054/dart_sdk.js:32205:29)
    at handleValueCallback (http://localhost:56054/dart_sdk.js:32752:49)
    at Function._propagateToListeners (http://localhost:56054/dart_sdk.js:32790:17)
    at _Future.new.[_completeWithValue] (http://localhost:56054/dart_sdk.js:32633:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:56054/dart_sdk.js:32655:35)
    at Object._microtaskLoop (http://localhost:56054/dart_sdk.js:37482:13)
    at _startMicrotaskLoop (http://localhost:56054/dart_sdk.js:37488:13)
    at http://localhost:56054/dart_sdk.js:33007:9Retry
```

**Comment by ryanheise** [comment]
This bug is fixed on the media-source branch (described here: #131 ).

**Comment by sunjianan9900** [comment]
thanks!
