### ISSUE TITLE
setAsset method fails if the file path contains '#'

### ISSUE THREAD

**Issue by ramaswag** [ryanheise/just_audio#1365]
**Which API doesn't behave as documented, and how does it misbehave?**
Exactly the same problem as here: https://github.com/ryanheise/just_audio/issues/77#issue-603374149 , but with the method setAsset()
I tried encoding the '#' with '%23' but it does not work.

**Minimal reproduction project**
(The same as the other issue)

**To Reproduce (i.e. user steps, not code)**
(The same as the other issue)

**Error messages**

```
E/ExoPlayerImplInternal(10985): Playback error
E/ExoPlayerImplInternal(10985):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal(10985):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)
E/ExoPlayerImplInternal(10985):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:614)
E/ExoPlayerImplInternal(10985):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal(10985):       at android.os.Looper.loopOnce(Looper.java:222)
E/ExoPlayerImplInternal(10985):       at android.os.Looper.loop(Looper.java:314)
E/ExoPlayerImplInternal(10985):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(10985):   Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (Mp3Extractor, FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, AviExtractor, JpegExtractor) could read the stream.
E/ExoPlayerImplInternal(10985):       at com.google.android.exoplayer2.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:92)
E/ExoPlayerImplInternal(10985):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1017)
E/ExoPlayerImplInternal(10985):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
E/ExoPlayerImplInternal(10985):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/ExoPlayerImplInternal(10985):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/ExoPlayerImplInternal(10985):       at java.lang.Thread.run(Thread.java:1012)
E/AudioPlayer(10985): TYPE_SOURCE: None of the available extractors (Mp3Extractor, FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, AviExtractor, JpegExtractor) could read the stream.
```

**Expected behavior**
The file is loaded as normally

**Screenshots**
no

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS + version]
 - Browser [e.g. chrome, safari + version]

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi Pro 5
 - OS: 

**Flutter SDK version**
```
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.6 23G80 darwin-x64, locale it-IT)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.2)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

**Additional context**
I need to load all notes sounds from a keyboard. All the notes that don't have '#' load correctly from assets

**Comment by richanshah** [comment]
@ramaswag  @ryanheise  any update on this ?
