### ISSUE TITLE
Error message when call setUrl()

### ISSUE THREAD

**Issue by erickcchoi** [ryanheise/just_audio#153]
**Which API doesn't behave as documented, and how does it misbehave?**
Error message when call setUrl() with uri ''http://s6.voscast.com:10922/;stream.nsv'',

**Minimal reproduction project**
```
import 'package:flutter/material.dart';
import 'package:just_audio/just_audio.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Example',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final player = AudioPlayer();
  bool playing = false;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            IconButton(
              icon: Icon((playing) ? Icons.pause : Icons.play_arrow),
              iconSize: 64.0,
              onPressed: () async {
                await player.setUrl('http://s6.voscast.com:10922/;stream.nsv');
                (playing) ? player.pause() : player.play();
                setState(() {
                  playing = !playing;
                });
              },
            ),
          ],
        ),
      ),
    );
  }
}
```
**To Reproduce (i.e. user steps, not code)**

**Error messages**

```
Debug service listening on ws://127.0.0.1:51238/4xw_d3jBznk=/ws
Syncing files to device Android SDK built for x86 64...
D/EGL_emulation( 8603): eglMakeCurrent: 0x796a657151e0: ver 2 0 (tinfo 0x796a1c039140)
W/just_audio_tes( 8603): Accessing hidden method Landroid/media/AudioTrack;->getLatency()I (greylist, reflection, allowed)
I/ExoPlayerImpl( 8603): Init 16ae915 [ExoPlayerLib/2.11.4] [generic_x86_64, Android SDK built for x86_64, Google, 29]
D/NetworkSecurityConfig( 8603): No Network Security Config specified, using platform default
I/VideoCapabilities( 8603): Unsupported profile 4 for video/mp4v-es
I/OMXClient( 8603): IOmx service obtained
I/flutter ( 8603): Error parsing event: type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'IcyHeaders'
I/flutter ( 8603): #0      new IcyMetadata.fromJson (package:just_audio/just_audio.dart:818:47)
I/flutter ( 8603): #1      new AudioPlayer._internal.<anonymous closure> (package:just_audio/just_audio.dart:122:29)
I/flutter ( 8603): #2      _MapStream._handleData (dart:async/stream_pipe.dart:219:31)
I/flutter ( 8603): #3      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:157:13)
I/flutter ( 8603): #4      _rootRunUnary (dart:async/zone.dart:1198:47)
I/flutter ( 8603): #5      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
I/flutter ( 8603): #6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
I/flutter ( 8603): #7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
I/flutter ( 8603): #8      _DelayedData.perform (dart:async/stream_impl.dart:611:14)
I/flutter ( 8603): #9      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
I/flutter ( 8603): #10     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
I/flutter ( 8603): #11     _rootRun (dart:async/zone.dart:1182:47)
I/flutter ( 8603): #12     _CustomZone.run (dart:async/zone.dart:1093:19)
I/flutter ( 8603): #13     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
I/flutter ( 8603): #14     _CustomZone.bindCallbackGuarded
I/ACodec  ( 8603): codec does not support config priority (err -2147483648)
I/flutter ( 8603): Error parsing event: type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'IcyHeaders'
I/flutter ( 8603): #0      new IcyMetadata.fromJson (package:just_audio/just_audio.dart:818:47)
I/flutter ( 8603): #1      new AudioPlayer._internal.<anonymous closure> (package:just_audio/just_audio.dart:122:29)
I/flutter ( 8603): #2      _MapStream._handleData (dart:async/stream_pipe.dart:219:31)
I/flutter ( 8603): #3      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:157:13)
I/flutter ( 8603): #4      _rootRunUnary (dart:async/zone.dart:1198:47)
I/flutter ( 8603): #5      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
I/flutter ( 8603): #6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
I/flutter ( 8603): #7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
I/flutter ( 8603): #8      _DelayedData.perform (dart:async/stream_impl.dart:611:14)
I/flutter ( 8603): #9      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
I/flutter ( 8603): #10     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
I/flutter ( 8603): #11     _rootRun (dart:async/zone.dart:1182:47)
I/flutter ( 8603): #12     _CustomZone.run (dart:async/zone.dart:1093:19)
I/flutter ( 8603): #13     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
I/flutter ( 8603): #14     _CustomZone.bindCallbackGuarded
I/flutter ( 8603): Error parsing event: type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'IcyInfo'
I/flutter ( 8603): #0      new IcyMetadata.fromJson (package:just_audio/just_audio.dart:818:24)
I/flutter ( 8603): #1      new AudioPlayer._internal.<anonymous closure> (package:just_audio/just_audio.dart:122:29)
I/flutter ( 8603): #2      _MapStream._handleData (dart:async/stream_pipe.dart:219:31)
I/flutter ( 8603): #3      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:157:13)
I/flutter ( 8603): #4      _rootRunUnary (dart:async/zone.dart:1198:47)
I/flutter ( 8603): #5      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
I/flutter ( 8603): #6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
I/flutter ( 8603): #7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
I/flutter ( 8603): #8      _DelayedData.perform (dart:async/stream_impl.dart:611:14)
I/flutter ( 8603): #9      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
I/flutter ( 8603): #10     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
I/flutter ( 8603): #11     _rootRun (dart:async/zone.dart:1182:47)
I/flutter ( 8603): #12     _CustomZone.run (dart:async/zone.dart:1093:19)
I/flutter ( 8603): #13     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
I/flutter ( 8603): #14     _CustomZone.bindCallbackGuarded
I/flutter ( 8603): Error parsing event: type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'IcyInfo'
I/flutter ( 8603): #0      new IcyMetadata.fromJson (package:just_audio/just_audio.dart:818:24)
I/flutter ( 8603): #1      new AudioPlayer._internal.<anonymous closure> (package:just_audio/just_audio.dart:122:29)
I/flutter ( 8603): #2      _MapStream._handleData (dart:async/stream_pipe.dart:219:31)
I/flutter ( 8603): #3      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:157:13)
I/flutter ( 8603): #4      _rootRunUnary (dart:async/zone.dart:1198:47)
I/flutter ( 8603): #5      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
I/flutter ( 8603): #6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
I/flutter ( 8603): #7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
I/flutter ( 8603): #8      _DelayedData.perform (dart:async/stream_impl.dart:611:14)
I/flutter ( 8603): #9      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
I/flutter ( 8603): #10     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
I/flutter ( 8603): #11     _rootRun (dart:async/zone.dart:1182:47)
I/flutter ( 8603): #12     _CustomZone.run (dart:async/zone.dart:1093:19)
I/flutter ( 8603): #13     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
I/flutter ( 8603): #14     _CustomZone.bindCallbackGuarded

```

**Expected behavior**
No error message when playing uri "http://s6.voscast.com:10922/;stream.nsv"

**Screenshots**
no

**Desktop (please complete the following information):**
 - OS: Windows 10 

**Smartphone (please complete the following information):**
 - Device: Android Simulator
 - OS: Android 10

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.19041.450], locale en-CA)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.47.2)
[√] Connected device (1 available)

• No issues found!
```

**Additional context**

**Comment by ryanheise** [comment]
Thanks, @erickcchoi I have fixed this on master. Can you test it?

**Comment by ryanheise** [comment]
Hi @erickcchoi , I have now released this as 0.3.4.

**Comment by zhubinsheng** [comment]
If you encounter this problem in other projects, it is valid to add the following

android:usesCleartextTraffic= "true"
android:networkSecurityConfig= "@xml/network_ security_ config

But after adding this library, I don't know what's going on. I still report an error. It's really strange

Caused by: java.io.IOException : Cleartext HTTP traffic to not permitted

**Comment by zhubinsheng** [comment]
Try changing targetsdkversion to 27. This works for me. The following settings don't work on Android P

android:usesCleartextTraffic= "true"

android:networkSecurityConfig= "@xml/network_ security_ config"

Reference links are as follows:

https://github.com/google/ExoPlayer/issues/4599
