### ISSUE TITLE
Bad state Exception when call player.dispose()

### ISSUE THREAD

**Issue by mahmood-heja** [ryanheise/just_audio#169]
when call dispose for **AudioPlayer** 

```
 @override
  void dispose() {
    player.dispose();

    super.dispose();
  }
```

the Bad state Exception happen 

> Unhandled Exception: Bad state: You cannot close the subject while items are being added from addStream
> E/flutter (29111): #0      Subject.close (package:rxdart/src/subjects/subject.dart:146:7)
> E/flutter (29111): #1      AudioPlayer.dispose (package:just_audio/just_audio.dart:681:30)

My  State class

```
class _ListAudioTileState extends State<ListAudioTile> {
  AudioPlayer player = AudioPlayer();
  Duration duration;

  @override
  void initState() {
    super.initState();

    intiAudio();
  }

  @override
  void dispose() {
    player.dispose();

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Card(
      margin: EdgeInsets.all(12.0),
      child: ListTile(
        leading: Container(
          height: 48,
          width: 48,
          child: Center(
            child: widget.audioCardW.iconUrl.isNotEmpty
                ? Image.network(widget.audioCardW.iconUrl)
                : Icon(
              Icons.library_music,
              size: 36,
            ),
          ),
        ),
        title: Text(widget.audioCardW.title ?? '',),
        subtitle: StreamBuilder<Duration>(
          stream: player.durationStream,
          builder: (context, snapshot) {
            final duration = snapshot.data ?? Duration.zero;
            return StreamBuilder<Duration>(
              stream: player.positionStream,
              builder: (context, snapshot) {
                Duration position = snapshot.data ?? Duration.zero;
                if (position > duration) {
                  position = duration;
                }
                return SeekBar(
                  duration: duration,
                  position: position,
                  onChangeEnd: (newPosition) {
                    player.seek(newPosition);
                  },
                );
              },
            );
          },
        ),
        trailing: StreamBuilder<PlayerState>(
          stream: player.playerStateStream,
          builder: (context, snapshot) {
            final playerState = snapshot.data;
            final processingState = playerState?.processingState;
            final playing = playerState?.playing;
            if (processingState == ProcessingState.loading ||
                processingState == ProcessingState.buffering) {
              return Container(
                margin: EdgeInsets.all(8.0),
                width: 32.0,
                height: 32.0,
                child: CircularProgressIndicator(),
              );
            } else if (playing != true) {
              return IconButton(
                icon: Icon(Icons.play_arrow),
                iconSize: 32.0,
                onPressed: player.play,
              );
            } else if (processingState != ProcessingState.completed) {
              return IconButton(
                icon: Icon(Icons.pause),
                iconSize: 24.0,
                onPressed: player.pause,
              );
            } else {
              return IconButton(
                icon: Icon(Icons.replay),
                iconSize: 24.0,
                onPressed: () => player.seek(Duration.zero, index: 0),
              );
            }
          },
        ),
      ),
    );
  }

  void intiAudio() async {
    final session = await AudioSession.instance;
    await session.configure(AudioSessionConfiguration.music(),);
    duration = await player.setUrl(widget.audioCardW.url ?? "");
  }


}

```

**Comment by dfdgsdfg** [comment]
Same here.

Seems to change as below.

```
  Future<void> dispose() async {
  // ..............
    if (_positionSubject != null) {
      await _positionSubject.drain();
      await _positionSubject.close();
    }
  }
```

Reference: https://stackoverflow.com/questions/52191451/bad-state-you-cannot-close-the-subject-while-items-are-being-added-from-addstre

**Comment by ryanheise** [comment]
@dfdgsdfg thanks for looking into this. Since this issue is closed would you mind posting a new issue? (Or perhaps if you're adventurous, a pull request?) By the way, I did at some point use the technique you referenced although removed it when I moved the responsibility of closing the event sink to the platform side. `_positionSubject`, however, is not directly bound to that event channel, it is bound to the stream returned by `createPositionStream` which in turn is closed via other code. So in theory, you do not need to close `_positionSubject` at all, and this line can just be deleted.

**Comment by ryanheise** [comment]
@kodi If you wouldn't mind, please create a new issue as per my previous comment. I will lock this issue to motivate people to listen carefully to what I am asking ;-)

**Comment by ryanheise** [comment]
To anyone subscribed to this issue, I have committed a potential fix to git master. The issue is being tracked on #183 .
