### ISSUE TITLE
failed to load local assets using setAsset()

### ISSUE THREAD

**Issue by RaphaelRevivor** [ryanheise/just_audio#196]
**Which API doesn't behave as documented, and how does it misbehave?**
setAsset() cannot load local assets. Generated an error: java.io.FileNotFoundException: assets/ding.wav

**Minimal reproduction project**
https://github.com/RaphaelRevivor/just_audio

**To Reproduce (i.e. user steps, not code)**
1. Run the Minimal reproduction project
2. Click on the Play button
3. See error
4. Or you can change the assets to "assets/clock.mp3" and repeat steps 1-3

**Error messages**

```
W/t_audio_exampl( 7502): Accessing hidden method Landroid/media/AudioTrack;->getLatency()I (greylist, reflection, allowed)
I/ExoPlayerImpl( 7502): Init 4fc5df [ExoPlayerLib/2.11.7] [OnePlus7Pro, GM1913, OnePlus, 29]
E/ExoPlayerImplInternal( 7502): Source error
E/ExoPlayerImplInternal( 7502):   com.google.android.exoplayer2.upstream.AssetDataSource$AssetDataSourceException: java.io.FileNotFoundException: assets/ding.wav
E/ExoPlayerImplInternal( 7502):       at com.google.android.exoplayer2.upstream.AssetDataSource.open(AssetDataSource.java:87)
E/ExoPlayerImplInternal( 7502):       at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:177)
E/ExoPlayerImplInternal( 7502):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
E/ExoPlayerImplInternal( 7502):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:962)
E/ExoPlayerImplInternal( 7502):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
E/ExoPlayerImplInternal( 7502):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal( 7502):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal( 7502):       at java.lang.Thread.run(Thread.java:919)
E/ExoPlayerImplInternal( 7502):   Caused by: java.io.FileNotFoundException: assets/ding.wav
E/ExoPlayerImplInternal( 7502):       at android.content.res.AssetManager.nativeOpenAsset(Native Method)
E/ExoPlayerImplInternal( 7502):       at android.content.res.AssetManager.open(AssetManager.java:833)
E/ExoPlayerImplInternal( 7502):       at com.google.android.exoplayer2.upstream.AssetDataSource.open(AssetDataSource.java:68)
E/ExoPlayerImplInternal( 7502):       ... 7 more
E/AudioPlayer( 7502): TYPE_SOURCE: java.io.FileNotFoundException: assets/ding.wav
E/flutter ( 7502): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: (0) com.google.android.exoplayer2.upstream.AssetDataSource$AssetDataSourceException: java.io.FileNotFoundException: assets/ding.wav
E/flutter ( 7502): #0      AudioPlayer._load 
package:just_audio/just_audio.dart:495
E/flutter ( 7502): <asynchronous suspension>
E/flutter ( 7502): #1      AudioPlayer.load 
package:just_audio/just_audio.dart:459
E/flutter ( 7502): #2      AudioPlayer.setAsset 
package:just_audio/just_audio.dart:444
E/flutter ( 7502): #3      _MyAppState.playMusic 
package:just_audio_example/main.dart:31
E/flutter ( 7502): #4      _MyAppState.build.<anonymous closure> 
package:just_audio_example/main.dart:48
E/flutter ( 7502): #5      _InkResponseState._handleTap 
package:flutter/…/material/ink_well.dart:992
E/flutter ( 7502): #6      _InkResponseState.build.<anonymous closure> 
package:flutter/…/material/ink_well.dart:1098
E/flutter ( 7502): #7      GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:184
E/flutter ( 7502): #8      TapGestureRecognizer.handleTapUp 
package:flutter/…/gestures/tap.dart:524
E/flutter ( 7502): #9      BaseTapGestureRecognizer._checkUp 
package:flutter/…/gestures/tap.dart:284
E/flutter ( 7502): #10     BaseTapGestureRecognizer.handlePrimaryPointer 
package:flutter/…/gestures/tap.dart:219
E/flutter ( 7502): #11     PrimaryPointerGestureRecognizer.handleEvent 
package:flutter/…/gestures/recognizer.dart:477
E/flutter ( 7502): #12     PointerRouter._dispatch 
package:flutter/…/gestures/pointer_router.dart:78
E/flutter ( 7502): #13     PointerRouter._dispatchEventToRoutes.<anonymous closure> 
package:flutter/…/gestures/pointer_router.dart:124
E/flutter ( 7502): #14     _LinkedHashMapMixin.forEach  (dart:collection-patch/compact_hash.dart:377:8))
E/flutter ( 7502): #15     PointerRouter._dispatchEventToRoutes 
package:flutter/…/gestures/pointer_router.dart:122
E/flutter ( 7502): #16     PointerRouter.route 
package:flutter/…/gestures/pointer_router.dart:108
E/flutter ( 7502): #17     GestureBinding.handleEvent 
package:flutter/…/gestures/binding.dart:220
E/flutter ( 7502): #18     GestureBinding.dispatchEvent 
package:flutter/…/gestures/binding.dart:200
E/flutter ( 7502): #19     GestureBinding._handlePointerEvent 
package:flutter/…/gestures/binding.dart:158
E/flutter ( 7502): #20     GestureBinding._flushPointerEventQueue 
package:flutter/…/gestures/binding.dart:104
E/flutter ( 7502): #21     GestureBinding._handlePointerDataPacket 
package:flutter/…/gestures/binding.dart:88
E/flutter ( 7502): #22     _rootRunUnary  (dart:async/zone.dart:1206:13))
E/flutter ( 7502): #23     _CustomZone.runUnary  (dart:async/zone.dart:1100:19))
E/flutter ( 7502): #24     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:1005:7))
E/flutter ( 7502): #25     _invoke1  (dart:ui/hooks.dart:267:10))
Launching lib\main.dart on GM1913 in debug mode...
✓ Built build\app\outputs\flutter-apk\app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:64367/9zDNb6wOqyI=/ws
W/t_audio_exampl( 7502): Accessing hidden method Landroid/media/AudioTrack;->getLatency()I (greylist, reflection, allowed)
I/ExoPlayerImpl( 7502): Init 4fc5df [ExoPlayerLib/2.11.7] [OnePlus7Pro, GM1913, OnePlus, 29]
E/ExoPlayerImplInternal( 7502): Source error
E/ExoPlayerImplInternal( 7502):   com.google.android.exoplayer2.upstream.AssetDataSource$AssetDataSourceException: java.io.FileNotFoundException: assets/ding.wav
E/ExoPlayerImplInternal( 7502):       at com.google.android.exoplayer2.upstream.AssetDataSource.open(AssetDataSource.java:87)
E/ExoPlayerImplInternal( 7502):       at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:177)
E/flutter ( 7502): #26     _dispatchPointerDataPacket  (dart:ui/hooks.dart:176:5))

```

**Expected behavior**
Should load local audio from assets

**Desktop (please complete the following information):**
 - OS: Windows 10 Home

**Smartphone (please complete the following information):**
 - Device: Oneplus 7 pro GM1913
 - OS: Android 10

**Flutter SDK version**
```
Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.20.2 at D:\flutter
    • Framework revision bbfbf1770c (7 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1
```

**Comment by ryanheise** [comment]
Hi @RaphaelRevivor , thanks for the bug report! Can you please try the latest release 0.5.1? It includes a fix for loading from assets.

**Comment by RaphaelRevivor** [comment]
Hi @ryanheise , thanks for the reply! I tested with 0.5.1 and the problem was solved. Issue closed.
