### ISSUE TITLE
No implementation found for method cancel on channel com.ryanheise.just_audio.events

### ISSUE THREAD

**Issue by pschuegr** [ryanheise/just_audio#274]
**Which API doesn't behave as documented, and how does it misbehave?**
I'm seeing a MissingPluginException occasionally.  I'm uncertain what is causing this yet or how to reproduce it, sorry!  Just thought I would post this in case it was helpful to you - I don't see the word "cancel" in very many places in the code.

`
════════ Exception caught by services library ══════════════════════════════════
The following MissingPluginException was thrown while de-activating platform stream on channel com.ryanheise.just_audio.events.e023926c-796e-4174-a2f8-5d17487a1884:
MissingPluginException(No implementation found for method cancel on channel com.ryanheise.just_audio.events.e023926c-796e-4174-a2f8-5d17487a1884)

When the exception was thrown, this was the stack
#0      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:160
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure>
package:flutter/…/services/platform_channel.dart:561
<asynchronous suspension>
════════════════════════════════════════════════════════════════════════════════
`

**Minimal reproduction project**
I'll post one as soon as I have isolated it.

**To Reproduce (i.e. user steps, not code)**
Not sure yet, sorry.

**Error messages**

`
════════ Exception caught by services library ══════════════════════════════════
The following MissingPluginException was thrown while de-activating platform stream on channel com.ryanheise.just_audio.events.e023926c-796e-4174-a2f8-5d17487a1884:
MissingPluginException(No implementation found for method cancel on channel com.ryanheise.just_audio.events.e023926c-796e-4174-a2f8-5d17487a1884)

When the exception was thrown, this was the stack
#0      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:160
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure>
package:flutter/…/services/platform_channel.dart:561
<asynchronous suspension>
════════════════════════════════════════════════════════════════════════════════
`

**Expected behavior**
No exception thrown.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 11.0.1
 - Browser [e.g. chrome, safari + version]

**Flutter SDK version**
```
[✓] Flutter (Channel dev, 1.26.0-1.0.pre, on macOS 11.0.1 20B29 darwin-x64, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.52.1)
[✓] Connected device (1 available)

• No issues found!
```

**Additional context**

**Comment by ryanheise** [comment]
Maybe related: https://github.com/flutter/flutter/issues/62006

However, your case might be different and it might be that the platform channels are working but then the error occurs when disposing the player. If that is the case, I look forward to your reproduction example.

You can also look in `darwin/Classes/AudioPlayer.m` and comment out these two lines at the bottom of the `dispose` method:

```objc
    // Untested:
    [_eventChannel setStreamHandler:nil];
    [_methodChannel setMethodCallHandler:nil];
```

Although hopefully that wouldn't introduce a memory leak.

**Comment by ryanheise** [comment]
A better solution may be in `_setPlatformActive` in `lib/just_audio.dart`:

```dart
      if (oldPlatformFuture != null) {
        final oldPlatform = await oldPlatformFuture;
        if (oldPlatform != _idlePlatform) {
          await _disposePlatform(oldPlatform);
        }
      }
      // ................ omitted code .......................
      _playbackEventSubscription?.cancel();
```

Once I can reproduce the error, I will try reordering the steps in this sequence so that the subscription is cancelled before the platform is disposed.

**Comment by pschuegr** [comment]
Thanks for the context link, I've already seen a lot of this error but I assume lots of it is my fault.  You're bang-on that it's not very descriptive though!

I've updated my original comment with repro steps.  My commit is unfortunately difficult to parse, but the only thing I changed from the `audio_service` example was to add an `await player.stop();` before `await player.dispose();`.  Obviously this is completely unnecessary in this example, but I saw this pretty consistently whenever I called `player.stop()` even if I wasn't about to dispose it.

**Comment by ryanheise** [comment]
Thanks @pschuegr , that will definitely be helpful. I will take a look.

**Comment by ryanheise** [comment]
Can you try the latest commit? Hopefully it should fix the issue.

**Comment by pschuegr** [comment]
Confirmed, thanks!

**Comment by ryanheise** [comment]
Great! You might like to pin your app to that git commit for now, as the next release might happen a few days later. I will post here once the next release comes out.

**Comment by pschuegr** [comment]
Thanks!

**Comment by adamkoch** [comment]
Was this fixed/closed? Or maybe there was a regression? I just switched over to just_audio after upgrading to flutter 2.0 and I am seeing the same crash. I am using just_audio 0.7.0.

Thanks!

**Comment by ryanheise** [comment]
Hi @adamkoch 

Thanks for reporting. I had forgotten to close this issue even though it was fixed. If there is a regression, can you confirm that the above reproduction project causes the error with 0.7.0? If not, are you able to provide another reproduction example?

**Comment by adamkoch** [comment]
Thanks for the fast response. I found the issue actually, I converted over from the [assets_audio_player](https://pub.dev/packages/assets_audio_player) package and was using this to dispose of the player:
```
  @override
  void dispose() {
    if (_audioPlayer != null) {
      _audioPlayer.stop();
      _audioPlayer.dispose();
    }
    super.dispose();
  }
```

This shows error:
```
======== Exception caught by services library ======================================================
The following MissingPluginException was thrown while de-activating platform stream on channel com.ryanheise.just_audio.events.86784fe5-23a9-41fb-9908-9f0309510324:
MissingPluginException(No implementation found for method cancel on channel com.ryanheise.just_audio.events.86784fe5-23a9-41fb-9908-9f0309510324)

When the exception was thrown, this was the stack: 
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:557:9)
<asynchronous suspension>
====================================================================================================
```

If I remove this or only call `dispose()` then the error doesn't show up. I guess as `stop()` the call may overlap with the `dispose()` call.

**Comment by ryanheise** [comment]
@adamkoch you have found the correct solution to your issue. The purpose of `stop()` in this plugin is to shut down the platform side of the plugin in a way that allows it to be resurrected later, but if you don't plan on resurrecting it, you would use `dispose()` instead. Although intuitively a `stop` followed by a `dispose` should also work without error. I suspect the reason you got an error was that you didn't `await` the first call before starting the second call. What I should probably do is guard against things like this inside the plugin, e.g. by queuing requests when order is important.

**Comment by adamkoch** [comment]
Makes sense, yes I didn't `await` the `stop()`. All is working for me now so you can close this issue. Although yes, ideally you would guard against things so this couldn't happen (block in `dispose()` if `stop()` is still running). Thanks for the fast and detailed responses!

**Comment by ryanheise** [comment]
I may leave this issue open still, just because I think I can improve things internally, and this will remind me to come back to this in the future.

**Comment by vietlinhtspt** [comment]
I close this issue by "flutter clean" and rebuild :))

**Comment by tianxiawoyougood** [comment]
Can this problem be improved? I received a lot of error messages in my log.

**Comment by tianxiawoyougood** [comment]
> Can this problem be improved? I received a lot of error messages in my log.

The iOS platform will report an error, but the Android platform will not report an error。
Why?

**Comment by ryanheise** [comment]
@tianxiawoyougood , a lot has changed in the plugin since this issue was created, so I'm not sure how comparable this is to your own situation. However, can you please try the PR #1488 and let me know if it still occurs?

**Comment by ryanheise** [comment]
That PR has now been merged and published. @tianxiawoyougood let me know if your issue persists.
