### ISSUE TITLE
Fatal Exception: com.google.android.exoplayer2.IllegalSeekPositionException

### ISSUE THREAD

**Issue by DenisShakinov** [ryanheise/just_audio#309]
**Which API doesn't behave as documented, and how does it misbehave?**
We've noticed a few random crashes in prod version of our app (Android). Here is stacktrace from firebase console:
```
Fatal Exception: com.google.android.exoplayer2.IllegalSeekPositionException
       at com.google.android.exoplayer2.ExoPlayerImpl.seekTo(ExoPlayerImpl.java:596)
       at com.google.android.exoplayer2.SimpleExoPlayer.seekTo(SimpleExoPlayer.java:1661)
       at com.ryanheise.just_audio.AudioPlayer.onPlayerError(AudioPlayer.java:271)
```

**Minimal reproduction project**
We are unable to reproduce such an issue on our available test devices so steps to reproduce are unclear

**To Reproduce (i.e. user steps, not code)**
(n/a)

**Error messages**
(n/a)

**Expected behavior**
App doesn't crash on any player error.

**Screenshots**
(n/a)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser (n/a)

**Smartphone (please complete the following information):**
 - Device: OPPO CPH1827
 - OS: Android 7.1.1

**Flutter SDK version**
```
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.0.1 20B50 darwin-x64, locale
    en-BY)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.53.2)
[✓] Connected device (2 available)
```

**Additional context**
I quess it may be some android api version or vendor specific issues (Operating systems: 96% Android 7, Devices: 69% OPPO, 25% LENOVO).
We don't do anything special with the library, just createPlayer -> setAsset -> play use case.

**Comment by AliHoseinpoor** [comment]
I have the same problem.
In crashes section in google play console i have this error
![Uploading IMG_20210312_113400.jpg…]()

**Comment by ryanheise** [comment]
Hi @AliHoseinpoor Can you confirm #310 fixes the issue?

I had unfortunately lost track of this issue during the null safety migration, but now that that's out of the way I can try to get this merged.

**Comment by AliHoseinpoor** [comment]
> Hi @AliHoseinpoor Can you confirm #310 fixes the issue?
> 
> I had unfortunately lost track of this issue during the null safety migration, but now that that's out of the way I can try to get this merged.

Hello my dear friend.
Unfortunately, I did not encounter the problem myself so that I could test it now. I was looking at my app crash statistics on Google Play when I saw that this error caused the app to crash a lot.

**Comment by ryanheise** [comment]
OK, I'll try to test and hopefully merge #310 on the latest just_audio version soon.

**Comment by AliHoseinpoor** [comment]
> OK, I'll try to test and hopefully merge #310 on the latest just_audio version soon.

Thank You very much

**Comment by DenisShakinov** [comment]
I was also quit busy past few weeks migrating all our apps to null safety so not keeping eye in this issue/PR. if you need anything from my side please welcome. I will also check our crash free statistic on firebase console (we are releasing today with #310 onboard) after release and get back to you soon.

**Comment by AliHoseinpoor** [comment]
> I was also quit busy past few weeks migrating all our apps to null safety so not keeping eye in this issue/PR. if you need anything from my side please welcome. I will also check our crash free statistic on firebase console (we are releasing today with #310 onboard) after release and get back to you soon.

Thank you very much for your kindness.
I myself have not encountered this problem in my tests, but it seems that the users of my application have encountered this problem.

**Comment by ryanheise** [comment]
I've just published the fix #310 in just_audio 0.7.1. Let me know if there are further issues, or if it turns out successful, I'll close the issue.

**Comment by DenisShakinov** [comment]
I quess we can close this. We've been using version 0.7.1+ for 2 months and it seems issue has gone.
