### ISSUE TITLE
[Feature] pass expo exceptions back to flutter

### ISSUE THREAD

**Issue by terryBaz** [ryanheise/just_audio#31]
_First, thank you for the plugin,_
I would like to have a possibility to know the exception that happened in expo player, so that I could catch a wrong url or 404 url ... (also related to https://github.com/ryanheise/just_audio/issues/29) .
Let me know if PR are welcome (I could help with this), for now I do have two solutions in mind : 
1. pass exceptions through a stream of errors
2. pass back the exception as a return (with duration, we create an object or use `.catchError(`) ) of `player.setUrl()`

thanks

**Comment by ryanheise** [comment]
Hi @terryBaz , yes I welcome pull requests. This is definitely an important feature.

I think it would make sense for `setUrl` to throw an exception and so a stream of errors on this occasion wouldn't be needed. This can be achieved on the platform side by sending an error through the platform channel. For example, on Android:

```java
prepareResult.error("error message", null, null);
```

And on iOS with this code:

```objc
_connectionResult([FlutterError errorWithCode:@"error message"
                                 message:nil
                                 details:nil]);

```

**Comment by terryBaz** [comment]
cool, that is what I started doing, but I am running into an issue with ExoPlayer State when I try to call `prepareResult.error(...)`, plz let me know if u have some hints

- the added code
```java
    @Override
    public void onPlayerError(ExoPlaybackException error) {
        switch (error.type) {
            case ExoPlaybackException.TYPE_SOURCE:
                Log.e(TAG, "TYPE_SOURCE: " + error.getSourceException().getMessage());
                this.setError(String.valueOf(error.type), error.getUnexpectedException().getMessage());
                break;

            case ExoPlaybackException.TYPE_RENDERER:
                Log.e(TAG, "TYPE_RENDERER: " + error.getRendererException().getMessage());
                break;

            case ExoPlaybackException.TYPE_UNEXPECTED:
                Log.e(TAG, "TYPE_UNEXPECTED: " + error.getUnexpectedException().getMessage());
                break;

            default:
                Log.e(TAG, "default: " + error.getUnexpectedException().getMessage());

        }
    }
....
    private void setError(String errorCode, String errorMsg) {
        this.dispose();
        if (prepareResult != null) {
            prepareResult.error(errorCode, errorMsg, null);
            prepareResult = null;
        }
    }
```
- the log from LogCat
```
02-01 12:09:11.942 20841-20841/com.ryanheise.just_audio_example E/AudioPlayer: TYPE_SOURCE: Response code: 404
02-01 12:09:11.946 20841-20841/com.ryanheise.just_audio_example E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ryanheise.just_audio_example, PID: 20841
    java.lang.IllegalStateException
        at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:81)
        at com.google.android.exoplayer2.ExoPlaybackException.getUnexpectedException(ExoPlaybackException.java:220)
        at com.ryanheise.just_audio.AudioPlayer.onPlayerError(AudioPlayer.java:135)
        at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.lambda$run$2$ExoPlayerImpl$PlaybackInfoUpdate(ExoPlayerImpl.java:812)
        at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$PlaybackInfoUpdate$fI_Ao37C4zouOtNaX7xHdRfgmVc.invokeListener(Unknown Source:2)
        at com.google.android.exoplayer2.BasePlayer$ListenerHolder.invoke(BasePlayer.java:182)
        at com.google.android.exoplayer2.ExoPlayerImpl.invokeAll(ExoPlayerImpl.java:845)
        at com.google.android.exoplayer2.ExoPlayerImpl.access$000(ExoPlayerImpl.java:43)
        at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.run(ExoPlayerImpl.java:812)
        at com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners(ExoPlayerImpl.java:736)
        at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:710)
        at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:652)
        at com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(ExoPlayerImpl.java:595)
        at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(ExoPlayerImpl.java:127)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7555)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
```

**Comment by terryBaz** [comment]
All fine, I figured out the issue, I will be preparing a PR soon.

**Comment by ryanheise** [comment]
Hi @terryBaz I'm curious about the code in your comment which is marked as "Resolved". Is that the code you were including in your PR?

**Comment by terryBaz** [comment]
I already find a solution for this and I am using it, but I still did not prepare a PR yet, sorry for that, did not have time for it, but I will try to prepare one Asap (hopefully in the next 2 days)

**Comment by ryanheise** [comment]
PR is now merged, thank you!
