### ISSUE TITLE
 createTrack returned error -12

### ISSUE THREAD

**Issue by alexgrusu** [ryanheise/just_audio#365]
**Which API doesn't behave as documented, and how does it misbehave?**
I use to play and pause multiple files during a game session.
After playing and pausing around 80 files, I encountered a crash of the audio library.
It seems that even re-initializing the player does not put the audio work again.

**Minimal reproduction project**
Provide a link here using one of two options:
1. I'm sorry but the project is private, working for a client.
2. Just call player?.play() and player?.pause() with a different player?.setAsset(asset)

**To Reproduce (i.e. user steps, not code)**
1. There are no user steps, everything is done in the background. A list of files is played during a game session.

**Error messages**

```
E/AudioTrack-JNI(30150): Error -12 initializing AudioTrack
D/AudioTrack(30150): gather(): no metrics gathered, track status=-12
E/android.media.AudioTrack(30150): Error code -20 when initializing AudioTrack.
E/ExoPlayerImplInternal(30150): Playback error
E/ExoPlayerImplInternal(30150):   com.google.android.exoplayer2.ExoPlaybackException: MediaCodecAudioRenderer error, index=1, format=Format(null, null, null, audio/raw, null, 705600, null, [-1, -1, -1.0], [1, 44100]), format_supported=YES
E/ExoPlayerImplInternal(30150):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)
E/ExoPlayerImplInternal(30150):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal(30150):       at android.os.Looper.loop(Looper.java:223)
E/ExoPlayerImplInternal(30150):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(30150):   Caused by: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed 0 Config(44100, 4, 22050)
E/ExoPlayerImplInternal(30150):       at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.buildAudioTrack(DefaultAudioSink.java:1981)
E/ExoPlayerImplInternal(30150):       at com.google.android.exoplayer2.audio.DefaultAudioSink.buildAudioTrack(DefaultAudioSink.java:821)
E/ExoPlayerImplInternal(30150):       at com.google.android.exoplayer2.audio.DefaultAudioSink.initializeAudioTrack(DefaultAudioSink.java:626)
E/ExoPlayerImplInternal(30150):       at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:699)
E/ExoPlayerImplInternal(30150):       at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:630)
E/ExoPlayerImplInternal(30150):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.bypassRender(MediaCodecRenderer.java:2155)
E/ExoPlayerImplInternal(30150):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:819)
E/ExoPlayerImplInternal(30150):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:947)
E/ExoPlayerImplInternal(30150):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:477)
E/ExoPlayerImplInternal(30150):       ... 3 more
E/ExoPlayerImplInternal(30150):       Suppressed: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed 0 Config(44100, 4, 22050)
E/ExoPlayerImplInternal(30150):           ... 12 more
E/ExoPlayerImplInternal(30150):       Caused by: java.lang.UnsupportedOperationException: Cannot create AudioTrack
E/ExoPlayerImplInternal(30150):           at android.media.AudioTrack$Builder.build(AudioTrack.java:1277)
E/ExoPlayerImplInternal(30150):           at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.createAudioTrackV29(DefaultAudioSink.java:2030)
E/ExoPlayerImplInternal(30150):           at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.createAudioTrack(DefaultAudioSink.java:2008)
E/ExoPlayerImplInternal(30150):           at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.buildAudioTrack(DefaultAudioSink.java:1973)
E/ExoPlayerImplInternal(30150):           ... 11 more
E/ExoPlayerImplInternal(30150):   Caused by: java.lang.UnsupportedOperationException: Cannot create AudioTrack
E/ExoPlayerImplInternal(30150):       at android.media.AudioTrack$Builder.build(AudioTrack.java:1277)
E/ExoPlayerImplInternal(30150):       at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.createAudioTrackV29(DefaultAudioSink.java:2030)
E/ExoPlayerImplInternal(30150):       at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.createAudioTrack(DefaultAudioSink.java:2008)
E/ExoPlayerImplInternal(30150):       at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.buildAudioTrack(DefaultAudioSink.java:1973)
E/ExoPlayerImplInternal(30150):       ... 11 more
E/AudioPlayer(30150): TYPE_RENDERER: AudioTrack init failed 0 Config(44100, 4, 22050)
 gather(): no metrics gathered, track status=-12
E/android.media.AudioTrack(30150): Error code -20 when initializing AudioTrack.
I/flutter (30150): AGR play Instance of 'AudioPlayer' playing=false,processingState=ProcessingState.ready

```

**Expected behavior**
Before null-safety it worked like a charm, without interruptions 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS + version]
 - Browser [e.g. chrome, safari + version]

**Smartphone (please complete the following information):**
 - Device: Pixel 2, API 30, emulator
 - OS: Android

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.2, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Chrome - develop for the web
[!] Android Studio
    ✗ android-studio-dir = /home/agr/Android
    ✗ Unable to find bundled Java version.
[✓] Android Studio
[✓] VS Code (version 1.54.3)
[✓] Connected device (3 available)

```

**Additional context**

**Comment by alexgrusu** [comment]
It seems to work fine on a Pixel 3a API 30 emulator.
Also, I tried to reproduce the behavior on a real device (Huawei p9 lite first version) and the issue didn't appear.

**Comment by ryanheise** [comment]
This most likely means you have hit the limit of how many audio tracks the operating system will allow to be open at once. This is a system wide limit and is affected by other apps which may also have audio tracks open. I don't know what the exact limit is, but 80 is much higher than I would have thought possible.

For game sound effects, you will probably want to use a different API such as sound pool.

**Comment by alexgrusu** [comment]
The assets are played separately one by one.
I have a player that plays the background music and another one that plays the voice and some warnings.

Tested on iPhone 7 and 8, everything works fine until now.

Now I'm wondering to not happen only on some devices.

**Comment by ryanheise** [comment]
A new track is created for each new player, and also if you stop the player and reuse that instance it will need to then recreate the track after that. So to limit the number of tracks you create, you need to either limit the number of instances you create or the number of times you call stop.

**Comment by alexgrusu** [comment]
On some devices work pretty well playing a few hundred files.

Is there another workaround if it is necessary to play so much files in a row?

**Comment by ryanheise** [comment]
Can you use a concatenating audio source?

**Comment by alexgrusu** [comment]
> Can you use a concatenating audio source?

If I use concatenation, am I able to control when a song must played or stopped? Also, is it possible to play a specific file from that concatenation?

**Comment by alexgrusu** [comment]
Found this in documentation

'''

await player.seek(Duration(milliseconds: 0), index: 2);

'''

It should be ok, I will try it and I will see if I have the control that I want.

**Comment by ryanheise** [comment]
I guess one issue may be that it will automatically continue playing to the next item after the current item finishes. It would probably be a good idea to have some sort of `autoAdvance` option which can be turned on/off.

**Comment by alexgrusu** [comment]
Ok, this could be a limitation so far. Some files require to be played when certain events occur. An option as you described could be helpful. Do you consider to implement it?

For cases when the OS limits the creation of tracks to a small number, could be this number determined? I'm thinking for an option to dispose the player and initialize a new one when the limit is reached. I saw that when the shown error occurs, even the reinitialization is not working.

**Comment by ryanheise** [comment]
I am not aware of any way to query the OS resource limits, so the only way is through testing on device.

The `autoAdvance` option would certainly be useful but it is not a high priority (there really are a lot of other big tasks that I need to focus on first, such as just_audio_background and the AVAudioEngine stuff). Someone else may need to help with a pull request to get this feature done sooner, but if you are so inclined, you might even consider becoming a project contributor yourself. It's usually possible to figure out how to modify the native code by looking at the surrounding code.

I would suggest for now implementing in your app a "player pool" where you always have a maximum number of player instances at any time.

**Comment by Chandu-bs** [comment]
Hi,

I have similar issue of **create track return error** and **audio initialization** error after playing for more than 4 or 5 times.
Can any one help me out with this coz tried different ways and checked the steps said above, but didn't worked out.

This is the error: 
`D/CCodecBufferChannel(15990): [c2.android.mp3.decoder#89] MediaCodec discarded an unknown buffer
I/chatty  (15990): uid=10154(com.bluesapience.risound) MediaCodec_loop identical 2 lines
D/CCodecBufferChannel(15990): [c2.android.mp3.decoder#89] MediaCodec discarded an unknown buffer
I/hw-BpHwBinder(15990): onLastStrongRef automatically unlinking death recipients
E/AudioPlayer(15990): TYPE_RENDERER: AudioTrack init failed 0 Config(44100, 12, 44100)
MediaCodecAudioRenderer error, index=1, format=Format(null, null, null, audio/raw, null, 705600, null, [-1, -1, -1.0], [1, 44100]), format_supported=YES`
