### ISSUE TITLE
Release mode `Unhandled Exception: (0) Source error`

### ISSUE THREAD

**Issue by nt4f04uNd** [ryanheise/just_audio#395]
**Which API doesn't behave as documented, and how does it misbehave?**
I'm not sure what's the source of this error, this needs investigation. Basically, bare app throws in release mode, but in debug it's fine

**Minimal reproduction project**
https://github.com/nt4f04unds-archive/issues/tree/audio_service_690

**To Reproduce (i.e. user steps, not code)**
Don't know

**Error messages**

```
E/flutter (19585): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: (0) Source error
E/flutter (19585): #0      AudioPlayer._load (package:just_audio/just_audio.dart:716)
E/flutter (19585): <asynchronous suspension>
E/flutter (19585): #1      AudioPlayer._setPlatformActive.setPlatform (package:just_audio/just_audio.dart:1096)
E/flutter (19585): <asynchronous suspension>
E/flutter (19585):
```

**Expected behavior**
No errors

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
 - Device: Redmi Note 5, Emulator
 - OS: Android 9, 11

**Flutter SDK version**
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel sweyer, 2.2.0-11.0.pre.158, on Microsoft Windows [Version 10.0.19041.928], locale ru-RU)
    • Flutter version 2.2.0-11.0.pre.158 at c:\dev\src\flutter
    • Upstream repository git@github.com:nt4f04und/flutter.git
    • Framework revision 1a5a05b7ae (2 weeks ago), 2021-04-06 05:14:02 +0800
    • Engine revision e3832e14b4
    • Dart version 2.14.0 (build 2.14.0-8.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\danya\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.55.2)
    • VS Code at C:\Users\danya\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Redmi Note 5 (mobile) • 40c9f14 • android-arm64  • Android 9 (API 28)
    • Windows (desktop)     • windows • windows-x64    • Microsoft Windows [Version 10.0.19041.928]
    • Chrome (web)          • chrome  • web-javascript • Google Chrome 89.0.4389.128
    • Edge (web)            • edge    • web-javascript • Microsoft Edge 89.0.774.77

• No issues found!
```
</details>

**Additional context**
No

**Comment by NiharDodiya** [comment]
Did you find any solution?

**Comment by NiharDodiya** [comment]
Any update on this issue?

**Comment by NiharDodiya** [comment]
@ryanheise

**Comment by nt4f04uNd** [comment]
This was a lack of internet permission lol

**Comment by ryanheise** [comment]
Ah, that makes perfect sense :-)

**Comment by nt4f04uNd** [comment]
By the way, maybe this is a good case for readme tip for people cracking their head around that?

**Comment by ryanheise** [comment]
That's probably a good idea.

**Comment by NiharDodiya** [comment]
But this is not happening every time with me. I already added internet permission and it working fine in one sound but not in another.

NOTE: Not facing this issue every time. And I'm using same method in whole project to load all audio files.

**Comment by ryanheise** [comment]
@NiharDodiya this error has many causes, and yours sounds like a different issue from @nt4f04uNd 's. Can you open a new bug report for your issue with steps on how to reproduce it?
