### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method setAndroidAudioAttributes)

### ISSUE THREAD

**Issue by xsylonteam** [ryanheise/just_audio#407]
**Which API doesn't behave as documented, and how does it misbehave?**
The app works fine in Android(it is already published in the play store and Sentry didn't report a single error yet.
Whatever I can't make it work in iOS, it stops right after the start with the following error, which is strange because the package shouldn't call any Android method when working with iOS.
I'm working with iOS simulator with an iPhone 12 Pro Max 14.4

**Minimal reproduction project**
The Example

**To Reproduce (i.e. user steps, not code)**
Just follow the example given steps.

**Error messages**

```
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method setAndroidAudioAttributes on channel com.ryanheise.just_audio.methods.50912f9f-32af-46b5-82fe-a4ed5bd31e9e)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
<asynchronous suspension>
#1      MethodChannelAudioPlayer.setAndroidAudioAttributes (package:just_audio_platform_interface/method_channel_just_audio.dart:112:10)
<asynchronous suspension>
#2      AudioPlayer._internalSetAndroidAudioAttributes (package:just_audio/just_audio.dart:962:5)
<asynchronous suspension>
#3      AudioPlayer.setAndroidAudioAttributes (package:just_audio/just_audio.dart:957:5)
<asynchronous suspension>
```

**Expected behavior**
Shouldn't suddenly stop.

**Desktop (please complete the following information):**
 - Mac OS X 10.15.7

**Smartphone (please complete the following information):**
 - iPhone 12 Pro Max
 - iOS 14.4

**Flutter SDK version**
```
[✓] Flutter (Channel stable, 2.2.0, on Mac OS X 10.15.7 19H524 darwin-x64, locale en)
    • Flutter version 2.2.0 at /Users/user928030/documents/flutter
    • Framework revision b22742018b (5 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/user928030/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2019.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7547

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • DDD5AEF0-BA69-4BE5-A9E1-56BA7A8215D3 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
```

**Additional context**
Nothing else to comment.

**Comment by ryanheise** [comment]
> Just follow the example given steps.

What steps? You didn't provide any.

> **Minimal reproduction project**
> The Example

Testing the example now...

**Comment by ryanheise** [comment]
I'm sorry, I've spent some time trying to reproduce this on the example and couldn't, but your reproduction steps were, let's say, vague. I tried just about everything I could with "The Example" and couldn't reproduce the issue.

**Comment by xsylonteam** [comment]
@ryanheise Sorry for the "vague" post, I was on a hurry and couldn't detail it a bit more, I will make a sample code and I will share it.

**Comment by ryanheise** [comment]
Why do you need sample code when you told me "The example" exhibits the bug?

**Comment by ryanheise** [comment]
I'll close this since it's been almost half a year without the bug report being filled in correctly. @jamesncl has offered some good advice for you to follow since he is right that this type of error typically points in the wrong direction.
