### ISSUE TITLE
Rewind with 3x throws the error in Android

### ISSUE THREAD

**Issue by Amrita-JSC** [ryanheise/just_audio#417]
**When i try to go backward with  _player.setSpeed(-3) in iOS it works fine but in Android it throws me an Error**

**Error messages**

```
W/System.err( 5510): java.lang.IllegalArgumentException
W/System.err( 5510): 	at com.google.android.exoplayer2.util.Assertions.checkArgument(Assertions.java:41)
W/System.err( 5510): 	at com.google.android.exoplayer2.PlaybackParameters.<init>(PlaybackParameters.java:56)
W/System.err( 5510): 	at com.google.android.exoplayer2.PlaybackParameters.<init>(PlaybackParameters.java:44)
W/System.err( 5510): 	at com.ryanheise.just_audio.AudioPlayer.setSpeed(AudioPlayer.java:677)
W/System.err( 5510): 	at com.ryanheise.just_audio.AudioPlayer.onMethodCall(AudioPlayer.java:311)
W/System.err( 5510): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
W/System.err( 5510): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
W/System.err( 5510): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
W/System.err( 5510): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err( 5510): 	at android.os.MessageQueue.next(MessageQueue.java:335)
W/System.err( 5510): 	at android.os.Looper.loop(Looper.java:183)
W/System.err( 5510): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
W/System.err( 5510): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 5510): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
W/System.err( 5510): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter ( 5510): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(Error: java.lang.IllegalArgumentException, null, null, null)
E/flutter ( 5510): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:581:7)
E/flutter ( 5510): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
E/flutter ( 5510): <asynchronous suspension>
E/flutter ( 5510): #2      MethodChannelAudioPlayer.setSpeed (package:just_audio_platform_interface/method_channel_just_audio.dart:67:38)
E/flutter ( 5510): <asynchronous suspension>
E/flutter ( 5510): #3      AudioPlayer.setSpeed (package:just_audio/just_audio.dart:868:5)
E/flutter ( 5510): <asynchronous suspension>
E/flutter ( 5510): 

```

**Comment by ryanheise** [comment]
Just to save you some effort in filling in a proper bug report, this is not a bug. Only positive values are supported for speed, although the iOS platform does happen to support negative values. Android does not support such a feature.
