### ISSUE TITLE
Crash on Android 5

### ISSUE THREAD

**Issue by armandojimenez** [ryanheise/just_audio#434]
**Which API doesn't behave as documented, and how does it misbehave?**
I don't know

**Minimal reproduction project**
It's a large project, only have logs on crashlytics 

**To Reproduce (i.e. user steps, not code)**
Can't reproduce, don't have Android 5 

**Error messages**

```
Fatal Exception: java.lang.RuntimeException: Unable to destroy activity {dev.armandojimenez.believe/dev.armandojimenez.believe.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void c.h.a.b.c()' on a null object reference
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4199)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4217)
       at android.app.ActivityThread.access$1500(ActivityThread.java:177)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1502)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5942)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1389)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1184)
```

**Expected behavior**
Don't crash

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS + version]
 - Browser [e.g. chrome, safari + version]

**Smartphone (please complete the following information):**
 - Device: Galaxy 4 and Galaxy Mini
 - OS: Android 5

**Flutter SDK version**
Dev channel latest
insert output of "flutter doctor" here
```

**Additional context**
Add any other context about the problem here.

**Comment by ryanheise** [comment]
I'm sorry, I won't be able to investigate unless you provide the information needed in the form, to establish if it is a bug in just audio, where in just audio, and how to reproduce it.

**Comment by ryanheise** [comment]
Please do open a new issue if you can provide the necessary information.
