### ISSUE TITLE
iOS command center next/previous buttons "Unhandled Exception: PlatformException(error, Error in handleMethodCall, null, null)"

### ISSUE THREAD

**Issue by dinithiviranga** [ryanheise/just_audio#464]
**Which API doesn't behave as documented, and how does it misbehave?**
just_audio_background

When trying to move to the next track after the last audio track was played, the app crashes

**Minimal reproduction project**
"The example" iOS project

**To Reproduce (i.e. user steps, not code)**
1. Click on the Play button in just_audio_background example
2. Go to background and open the command center by pulling from top of the screen.
3. Click on 'Skip Next' button until the playlist is over.
4. The play button on the command center is disabled now.
4. The app crashes with the below error when we click on the 'Skip next' button (after the last audio track) and try to click on the play button .

**Error messages**

```
2021-07-29 15:56:49.502379+0530 Runner[33015:337501] ### MPNowPlayingInfoPropertyElapsedPlaybackTime = '0.001'
2021-07-29 15:56:49.502596+0530 Runner[33015:337501] ### updating nowPlayingInfo
2021-07-29 15:56:49.591848+0530 Runner[33015:337501] ### title = 'Nature Sounds'
2021-07-29 15:56:49.591989+0530 Runner[33015:337501] ### albumTitle = 'Public Domain'
2021-07-29 15:56:49.592091+0530 Runner[33015:337501] ### artist = nil
2021-07-29 15:56:49.592191+0530 Runner[33015:337501] ### playbackDuration = '3.709'
2021-07-29 15:56:49.592347+0530 Runner[33015:337501] ### artwork = '<MPMediaItemArtwork: 0x60000221bc60>'
2021-07-29 15:56:49.592463+0530 Runner[33015:337501] ### updating nowPlayingInfo
2021-07-29 15:56:50.139081+0530 Runner[33015:337501] nextTrack
2021-07-29 15:56:50.142651+0530 Runner[33015:337646] [VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: PlatformException(error, Error in handleMethodCall, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
<asynchronous suspension>
#2      MethodChannelAudioPlayer.seek (package:just_audio_platform_interface/method_channel_just_audio.dart:144:34)
<asynchronous suspension>
2021-07-29 15:56:55.178977+0530 Runner[33015:337501] nextTrack
2021-07-29 15:56:55.180067+0530 Runner[33015:337646] [VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: PlatformException(error, Error in handleMethodCall, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
<asynchronous suspension>
#2      MethodChannelAudioPlayer.seek (package:just_audio_platform_interface/method_channel_just_audio.dart:144:34)
<asynchronous suspension>
2021-07-29 15:56:57.245553+0530 Runner[33015:337501] pause
2021-07-29 15:56:57.246761+0530 Runner[33015:337501] ## updateControl 1 enable=0
2021-07-29 15:56:57.247713+0530 Runner[33015:337501] ## updateControl 2 enable=1
2021-07-29 15:56:57.247897+0530 Runner[33015:337501] ### artist = nil
2021-07-29 15:56:57.248008+0530 Runner[33015:337501] ### MPNowPlayingInfoPropertyPlaybackRate = '0'
2021-07-29 15:56:57.248181+0530 Runner[33015:337501] ### MPNowPlayingInfoPropertyElapsedPlaybackTime = '7.747'
2021-07-29 15:56:57.248342+0530 Runner[33015:337501] ### updating nowPlayingInfo
2021-07-29 15:57:00.091647+0530 Runner[33015:337501] play
2021-07-29 15:57:00.092712+0530 Runner[33015:337501] ## updateControl 1 enable=1
2021-07-29 15:57:00.096989+0530 Runner[33015:337501] ## updateControl 2 enable=0
2021-07-29 15:57:00.097147+0530 Runner[33015:337501] ### artist = nil
2021-07-29 15:57:00.097319+0530 Runner[33015:337501] ### MPNowPlayingInfoPropertyPlaybackRate = '1'
2021-07-29 15:57:00.098434+0530 Runner[33015:337501] ### updating nowPlayingInfo
2021-07-29 15:57:00.100698+0530 Runner[33015:337501] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndexedSubscript:]: index 4 beyond bounds [0 .. 3]'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff20421af6 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20177e78 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff2049e77f _CFThrowFormattedException + 194
	3   CoreFoundation                      0x00007fff20320825 -[__NSArrayM removeAllObjects] + 0
	4   just_audio                          0x000000010e5118e9 -[AudioPlayer getBufferedPosition] + 137
	5   just_audio                          0x000000010e511446 -[AudioPlayer broadcastPlaybackEvent] + 294
	6   just_audio                          0x000000010e51637d -[AudioPlayer observeValueForKeyPath:ofObject:change:context:] + 3709
	7   Foundation                          0x00007fff207bf6f4 NSKeyValueNotifyObserver + 329
	8   Foundation                          0x00007fff207c2e28 NSKeyValueDidChange + 439
	9   Foundation                          0x00007fff207bebff NSKeyValueDidChangeWithPerThreadPendingNotifications + 146
	10  AVFCore                             0x00007fff5915e6be __avplayer_fpNotificationCallback_block_invoke + 1562
	11  libdispatch.dylib                   0x00000001109847ec _dispatch_call_block_and_release + 12
	12  libdispatch.dylib                   0x00000001109859c8 _dispatch_client_callout + 8
	13  libdispatch.dylib                   0x0000000110993e75 _dispatch_main_queue_callback_4CF + 1152
	14  CoreFoundation                      0x00007fff2038fdbb __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	15  CoreFoundation                      0x00007fff2038a63e __CFRunLoopRun + 2685
	16  CoreFoundation                      0x00007fff203896d6 CFRunLoopRunSpecific + 567
	17  GraphicsServices                    0x00007fff2c257db3 GSEventRunModal + 139
	18  UIKitCore                           0x00007fff24696cf7 -[UIApplication _run] + 912
	19  UIKitCore                           0x00007fff2469bba8 UIApplicationMain + 101
	20  Runner                              0x000000010e229a30 main + 112
	21  libdyld.dylib                       0x00007fff2025a3e9 start + 1
	22  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndexedSubscript:]: index 4 beyond bounds [0 .. 3]'
CoreSimulator 732.18.6 - Device: iPhone 12 Pro Max (BA6DAB29-B8A6-4012-8B50-599196848B6D) - Runtime: iOS 14.4 (18D46) - DeviceType: iPhone 12 Pro Max
terminating with uncaught exception of type NSException
```

**Expected behavior**
The skip button in the command center should be disabled if the playlist doesn't have a next track.

**Screenshots**

**Smartphone **
 - Device: [e.g. iPhone7+]
 - OS: [e.g. iOS14.4]

**Flutter SDK version**
```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.3.1 20E241 darwin-x64, locale
    en-LK)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.58.2)
[✓] Connected device (3 available)

• No issues found!

```
![IMG_5162](https://user-images.githubusercontent.com/8285865/127479750-5ba29beb-7f0d-42fd-a7e5-591d5649436e.PNG)

**Comment by ryanheise** [comment]
Thanks for the report, I'll take a look when I get a chance.

**Comment by ryanheise** [comment]
Can you try the branch `fix/queue` and let me know if it's fixed?

**Comment by dinithiviranga** [comment]
Yes, it is fixed in the fix/queue branch. Thanks a lot.

**Comment by ryanheise** [comment]
Thanks for testing! I have now published it in the latest release.
