### ISSUE TITLE
Catching CodecExceptions from ExoPlayer

### ISSUE THREAD

**Issue by BeMacized** [ryanheise/just_audio#48]
Currently, when I feed the plugin a url to an online audio file in opus format, ExoPlayer throws the following exception:

<details><summary>Exception</summary>
<p>

```
E/ExoPlayerImplInternal(10334): Renderer error: index=1, type=audio, format=Format(1, null, null, audio/opus, null, -1, en, [-1, -1, -1.0], [2, 48000]), rendererSupport=YES
E/ExoPlayerImplInternal(10334): com.google.android.exoplayer2.ExoPlaybackException: android.media.MediaCodec$CodecException: Error 0x80000000
E/ExoPlayerImplInternal(10334): 	at com.google.android.exoplayer2.BaseRenderer.createRendererException(BaseRenderer.java:359)
E/ExoPlayerImplInternal(10334): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:723)
E/ExoPlayerImplInternal(10334): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599)
E/ExoPlayerImplInternal(10334): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329)
E/ExoPlayerImplInternal(10334): 	at android.os.Handler.dispatchMessage(Handler.java:103)
E/ExoPlayerImplInternal(10334): 	at android.os.Looper.loop(Looper.java:214)
E/ExoPlayerImplInternal(10334): 	at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(10334): Caused by: android.media.MediaCodec$CodecException: Error 0x80000000
E/ExoPlayerImplInternal(10334): 	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
E/ExoPlayerImplInternal(10334): 	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2823)
E/ExoPlayerImplInternal(10334): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1504)
E/ExoPlayerImplInternal(10334): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:709)
E/ExoPlayerImplInternal(10334): 	... 5 more
```
[Surrounding logs here](https://pastebin.com/DcF22xDu)
</p>
</details>

I guess this has more something to do with ExoPlayer than just_audio, but the problem I am having is that I seem to have no way of catching this exception. 

Is there any way I can handle these cases?

**Comment by ryanheise** [comment]
Hi @BeMacized I don't recall whether the error catching code in just_audio was there when you reported this bug, but is this still a problem? And if it is, do you have a URL file that I can test?

I also don't remember whether I updated the version of ExoPlayer since you filed this bug, so it is also possible that the current version of ExoPlayer no longer has this issue.

**Comment by sarbazx** [comment]
Hi @ryanheise I am also getting exception when url is in opus format

```
flutter: Error: (-11850) Operation Stopped
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: PlatformException(-11850, Operation Stopped, null, null)
```

**Comment by ryanheise** [comment]
@sarbazx do you have a URL I can test?

**Comment by sarbazx** [comment]
@ryanheise is there any private channel so I can share with you? I do not want publicly share the link.

**Comment by ryanheise** [comment]
You can send it via [email](https://pub.dev/publishers/ryanheise.com/packages).

**Comment by ryanheise** [comment]
I have just tested with the opus sample file at https://docs.espressif.com/projects/esp-adf/en/latest/design-guide/audio-samples.html and it worked, so it sounds like it's dependent on the particular opus file.

@sarbazx I did check out the opus file you emailed me and can confirm the error. I've upgraded just_audio to the latest ExoPlayer dependency and that also didn't fix it, so you will also need to correspond directly with the authors of ExoPlayer with a sample opus file that fails. You can file a bug directly with the ExoPlayer project here:

https://github.com/google/ExoPlayer/issues

Regarding the ability to catch this error, the latest version of just_audio should allow you to do that by placing a try/catch around the `await setUrl` (or similar) call.

**Comment by sarbazx** [comment]
Hi @ryanheise thanks for checking out, I have looked into exoplayer issue and found this issue https://github.com/google/ExoPlayer/issues/7046 
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/5629946/102453028-7b953400-404c-11eb-834e-790740b0f090.png">

does this mean they have fixed in latest version or it is not yet published?

**Comment by ryanheise** [comment]
The fix is published, and just_audio is now using it in the latest git commit.

It is possible their fix isn't a complete fix, or that your issue is a different error with similar symptoms, or that they did fix the bug but reintroduced the bug in a later commit.

**Comment by ryanheise** [comment]
Just checking the jar files included with just_audio, it it seems (to my surprise) that the opus decoder is not included by default. For that matter, (unless I'm not checking correctly), the FLAC decoder is also not included by default, despite ojw28 saying that it would now be possible to use it without having to add any extensions.

I'll have to look into this further.

**Comment by ryanheise** [comment]
OK, so looking at the code, it seems for both Opus and FLAC, there should be some basic built-in support.

However, full support seems to require the extensions.

Both extensions are BSD-licensed which I should be able to incorporate.

The only thing I need to find is the best way to include ExoPlayer extensions in a Flutter plugin.

In the meantime, you can look at the approach taken in #32 , or of course you can add the extension if you download your own copy of ExoPlayer locally and follow ExoPlayer's instructions.
