### ISSUE TITLE
Can't Play Local Audio Files On Android

### ISSUE THREAD

**Issue by RalphMarvin** [ryanheise/just_audio#481]
I'm trying to play a local file but it doesn't work. Below is the error message I'm getting:
This is the file path am passing: `/storage/1818-3D1B/Music/2. Suffering From Success (Feat. Future & Ace Hood).mp3`

```
I/ExoPlayerImpl(10275): Init d7ad958 [ExoPlayerLib/2.13.1] [generic_x86, Android SDK built for x86, Google, 29]
E/ExoPlayerImplInternal(10275): Playback error
E/ExoPlayerImplInternal(10275):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal(10275):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:579)
E/ExoPlayerImplInternal(10275):       at android.os.Handler.dispatchMessage(Handler.java:103)
E/ExoPlayerImplInternal(10275):       at android.os.Looper.loop(Looper.java:214)
E/ExoPlayerImplInternal(10275):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(10275):   Caused by: com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: java.io.FileNotFoundException: /storage/1818-3D1B/Music/2. Suffering From Success (Feat. Future & Ace Hood).mp3: open failed: EACCES (Permission denied)
E/ExoPlayerImplInternal(10275):       at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:97)
E/ExoPlayerImplInternal(10275):       at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:201)
E/ExoPlayerImplInternal(10275):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
E/ExoPlayerImplInternal(10275):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1015)
E/ExoPlayerImplInternal(10275):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
E/ExoPlayerImplInternal(10275):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal(10275):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal(10275):       at java.lang.Thread.run(Thread.java:919)
E/ExoPlayerImplInternal(10275):   Caused by: com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: java.io.FileNotFoundException: /storage/1818-3D1B/Music/2. Suffering From Success (Feat. Future & Ace 
Hood).mp3: open failed: EACCES (Permission denied)
E/ExoPlayerImplInternal(10275):       at com.google.android.exoplayer2.upstream.FileDataSource.openLocalFile(FileDataSource.java:166)
E/ExoPlayerImplInternal(10275):       at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:89)
E/ExoPlayerImplInternal(10275):       ... 7 more
E/ExoPlayerImplInternal(10275):   Caused by: java.io.FileNotFoundException: /storage/1818-3D1B/Music/2. Suffering From Success (Feat. Future & Ace Hood).mp3: open failed: EACCES (Permission denied)
E/ExoPlayerImplInternal(10275):       at libcore.io.IoBridge.open(IoBridge.java:496)
E/ExoPlayerImplInternal(10275):       at java.io.RandomAccessFile.<init>(RandomAccessFile.java:289)
E/ExoPlayerImplInternal(10275):       at java.io.RandomAccessFile.<init>(RandomAccessFile.java:152)
E/ExoPlayerImplInternal(10275):       at com.google.android.exoplayer2.upstream.FileDataSource.openLocalFile(FileDataSource.java:155)
E/ExoPlayerImplInternal(10275):       ... 8 more
E/ExoPlayerImplInternal(10275):   Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
E/ExoPlayerImplInternal(10275):       at libcore.io.Linux.open(Native Method)
E/ExoPlayerImplInternal(10275):       at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
E/ExoPlayerImplInternal(10275):       at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
E/ExoPlayerImplInternal(10275):       at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
E/ExoPlayerImplInternal(10275):       at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7255)     
E/ExoPlayerImplInternal(10275):       at libcore.io.IoBridge.open(IoBridge.java:482)
E/ExoPlayerImplInternal(10275):       ... 11 more
E/AudioPlayer(10275): TYPE_SOURCE: com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: java.io.FileNotFoundException: /storage/1818-3D1B/Music/2. Suffering From Success (Feat. Future & Ace Hood).mp3: open failed: EACCES (Permission denied)
I/ExoPlayerImpl(10275): Release d7ad958 [ExoPlayerLib/2.13.1] [generic_x86, Android SDK built for x86, Google, 29] [goog.exo.core]
I/ExoPlayerImpl(10275): Init 6f280a5 [ExoPlayerLib/2.13.1] [generic_x86, Android SDK built for x86, Google, 29]
E/flutter (10275): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: (0) Source error
E/flutter (10275): #0      AudioPlayer._load (package:just_audio/just_audio.dart:784:9)
E/flutter (10275): <asynchronous suspension>
E/flutter (10275): #1      AudioPlayer._setPlatformActive.setPlatform (package:just_audio/just_audio.dart:1342:28)
E/flutter (10275): <asynchronous suspension>
E/flutter (10275): #2      AudioPlayer.play (package:just_audio/just_audio.dart:857:28)
E/flutter (10275): <asynchronous suspension>
```

**Comment by ryanheise** [comment]
Just to save you some effort, this is not a just_audio bug, but rather you either have the wrong file URI or you have the right file URI but not the right [permissions](https://pub.dev/packages/permission_handler). If the latter case, it's an issue with how you use that plugin rather than this one.
