### ISSUE TITLE
Seek fails on big audio file on Android

### ISSUE THREAD

**Issue by jcblancomartinez** [ryanheise/just_audio#679]
**Which API doesn't behave as documented, and how does it misbehave?**
Seek API. When calling seek on big audio file on Android, it fails with ExoPlaybackException.
Additionally, there is no way to catch the exception in Flutter code. I tried the following but 'Failed' doesn't get printed upon ExoPlaybackException.

`_player.seek(duration).then(
                        (value) => print('Succeeded'),
                        onError: (dynamic error, StackTrace? stackTrace) =>
                            print('Failed'))`

**Minimal reproduction project**
Please, find [here](https://github.com/jcblancomartinez/just_audio/blob/72b73e2752e966f08f0193fbffdbbd14c4072f5c/just_audio/example/lib/main.dart) the modified repo.

**To Reproduce (i.e. user steps, not code)**
1. Click on play
2. Click on the progress bar to jump to the position where 12:00 minutes of the audio are left.
3. See error

**Error messages**

```
W/DefaultLoadControl( 5005): Target buffer size reached with less than 500ms of buffered media data.
W/DefaultLoadControl( 5005): Target buffer size reached with less than 500ms of buffered media data.
E/ExoPlayerImplInternal( 5005): Playback error
E/ExoPlayerImplInternal( 5005):   com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
E/ExoPlayerImplInternal( 5005):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:608)
E/ExoPlayerImplInternal( 5005):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal( 5005):       at android.os.Looper.loopOnce(Looper.java:201)
E/ExoPlayerImplInternal( 5005):       at android.os.Looper.loop(Looper.java:288)
E/ExoPlayerImplInternal( 5005):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal( 5005):   Caused by: java.lang.IllegalStateException: Playback stuck buffering and not loading
E/ExoPlayerImplInternal( 5005):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1046)
E/ExoPlayerImplInternal( 5005):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:482)
E/ExoPlayerImplInternal( 5005):       ... 4 more
I/CCodecConfig( 5005): query failed after returning 7 values (BAD_INDEX)
W/Codec2Client( 5005): query -- param skipped: index = 1342179345.
W/Codec2Client( 5005): query -- param skipped: index = 2415921170.
D/CCodecBufferChannel( 5005): [c2.android.mp3.decoder#290] MediaCodec discarded an unknown buffer
D/CCodecBufferChannel( 5005): [c2.android.mp3.decoder#290] MediaCodec discarded an unknown buffer
D/CCodecBufferChannel( 5005): [c2.android.mp3.decoder#290] MediaCodec discarded an unknown buffer
D/CCodecBufferChannel( 5005): [c2.android.mp3.decoder#290] MediaCodec discarded an unknown buffer
I/hw-BpHwBinder( 5005): onLastStrongRef automatically unlinking death recipients
E/AudioPlayer( 5005): TYPE_UNEXPECTED: Playback stuck buffering and not loading
I/flutter ( 5005): A stream error occurred: PlatformException(2, Unexpected runtime error, null, null)
```

**Expected behavior**
I would expect the audio to start playing in that position.

**Screenshots**
After the exception is thrown, a spinner gets shown instead of the play button.

![Screenshot1](https://user-images.githubusercontent.com/1192455/158244971-7403ae98-df3c-4c37-82ca-bc5f64cbb2f5.png)

**Desktop (please complete the following information):**
 - OS: N/A
 - Browser: N/A

**Smartphone (please complete the following information):**
 - Device: POCO M3 Pro 5G
 - OS: Android 11

**Flutter SDK version**
```
[✓] Flutter (Channel stable, 2.10.3, on Ubuntu 20.04.3 LTS 5.13.0-35-generic,
    locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version
    32.0.0-rc1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

```

**Comment by jcblancomartinez** [comment]
Hi @ryanheise ,

Thanks for your work on this plugin.

This is the only issue preventing me from onboarding this plugin.

Could you please let me know if this would be an easy fix?

Thanks.

Best regards.

**Comment by ryanheise** [comment]
> Additionally, there is no way to catch the exception in Flutter code.

Your log shows "a stream error occurred" which indicates that it is being caught by Flutter.

If the error is still an issue for you, you may need to report it upstream with Google's exoplayer since that appears to be the actual behaviour of exoplayer. They may also be able to advise you on alternative audio encodings you can try since seeking behaviour is dependent on the encoding.

**Comment by ryanheise** [comment]
I notice that your example is based on MP3, and it is worth noting that that format is not suitable for seeking in general and especially for very long audio.

**Comment by jcblancomartinez** [comment]
How would you catch the exception to show an error message and replace spinner with play button?

Thanks.

**Comment by ryanheise** [comment]
In terms of how to catch the exception, you already did that in your example which is what I pointed out in my first comment with your "A stream error occurred" printout. I would have thought it's a simple matter of replacing that one line of code that prints "A stream error occurred" with your own code to display whatever it is you want to display.

In any case this bug report is related to the seek behaviour, and I would say that catching the error doesn't actually solve the problem. To solve the problem, I suggest you look at the way upstream ExoPlayer behaves with long mp3 files and consider using a different encoding.

**Comment by jcblancomartinez** [comment]
Regarding catching the error, sorry for the confusion brought.

You are right, the exception is being caught and printed [here](https://github.com/jcblancomartinez/just_audio/blob/72b73e2752e966f08f0193fbffdbbd14c4072f5c/just_audio/example/lib/main.dart#L40).

Thanks.

**Comment by jcblancomartinez** [comment]
The following configuration solved my issue:

`AudioPlayer(
                audioLoadConfiguration: AudioLoadConfiguration(
                    androidLoadControl: AndroidLoadControl(
                        prioritizeTimeOverSizeThresholds: true
                    )))`

Thanks.
