### ISSUE TITLE
I have a problem with handle deep linking

### ISSUE THREAD

**Issue by o4x** [ryanheise/just_audio#69]
I found no way to use deep linking with this.
I add this to `AndroidManifest.xml` : 
```
            <intent-filter>
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:scheme="content"/>
                <data android:scheme="file"/>
                <data android:mimeType="audio/*"/>
                <data android:mimeType="application/x-flac"/>
                <data android:mimeType="application/ogg"/>
                <data android:mimeType="application/x-ogg"/>
                <data android:mimeType="application/itunes"/>
            </intent-filter>
```
It work but when I try open my app with open with, I get this error :
```
Accessing hidden method Landroid/media/AudioTrack;->getLatency()I (light greylist, reflection)
I/ExoPlayerImpl(10126): Init e9b0b92 [ExoPlayerLib/2.11.1] [generic_x86_arm, AOSP on IA Emulator, Google, 28]
W/System.err(10126): java.lang.IllegalStateException: Cannot call play from connecting/none states (none)
W/System.err(10126): 	at com.ryanheise.just_audio.AudioPlayer.play(AudioPlayer.java:306)
W/System.err(10126): 	at com.ryanheise.just_audio.AudioPlayer.onMethodCall(AudioPlayer.java:181)
W/System.err(10126): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
W/System.err(10126): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
W/System.err(10126): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
W/System.err(10126): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err(10126): 	at android.os.MessageQueue.next(MessageQueue.java:326)
W/System.err(10126): 	at android.os.Looper.loop(Looper.java:160)
W/System.err(10126): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
W/System.err(10126): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(10126): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
W/System.err(10126): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/flutter (10126): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(Illegal state: Cannot call play from connecting/none states (none), null, null)
E/flutter (10126): #0      StandardMethodCodec.decodeEnvelope 
package:flutter/…/services/message_codecs.dart:569
E/flutter (10126): #1      MethodChannel.invokeMethod 
package:flutter/…/services/platform_channel.dart:321
E/flutter (10126): <asynchronous suspension>
E/flutter (10126): #2      AudioPlayer._invokeMethod 
package:just_audio/just_audio.dart:320
E/flutter (10126): <asynchronous suspension>
E/flutter (10126): #3      AudioPlayer.play 
package:just_audio/just_audio.dart:253
E/flutter (10126): #4      CustomAudioPlayer.onPlay 
package:musical/audio/audio_service.dart:167
E/flutter (10126): #5      CustomAudioPlayer.onCustomAction 
package:musical/audio/audio_service.dart:260
E/flutter (10126): <asynchronous suspension>
E/flutter (10126): #6      AudioServiceBackground.run.<anonymous closure> 
package:audio_service/audio_service.dart:852
E/flutter (10126): #7      MethodChannel._handleAsMethodCall 
package:flutter/…/services/platform_channel.dart:402
E/flutter (10126): #8      MethodChannel.setMethodCallHandler.<anonymous closure> 
package:flutter/…/services/platform_channel.dart:370
E/flutter (10126): #9      _DefaultBinaryMessenger.handlePlatformMessage 
package:flutter/…/services/binding.dart:200
E/flutter (10126): #10     _invoke3.<anonymous closure>  (dart:ui/hooks.dart:303:15)
E/flutter (10126): #11     _rootRun  (dart:async/zone.dart:1126:13)
E/flutter (10126): #12     _CustomZone.run  (dart:async/zone.dart:1023:19)
E/flutter (10126): #13     _CustomZone.runGuarded  (dart:async/zone.dart:925:7)
E/flutter (10126): #14     _invoke3  (dart:ui/hooks.dart:302:10)
E/flutter (10126): #15     _dispatchPlatformMessage  (dart:ui/hooks.dart:162:5)
```

**Comment by ryanheise** [comment]
Hi @o4x can I just understand what state the player is in when you call `play`? The documentation says that you must not call it from the connecting or none states. Currently, the best way to ensure that the player is ready to play is to "await" the result of `setUrl` (or one of the alternative methods like `setFilePath` or `setAsset` depending on which one you use). For example:

```dart
await player.setUrl('https://foo.com/bar.mp3');
player.play();
```
I would be interested to know what state the player is in when you call `play`, so perhaps you could try printing it out for me the line before you play the audio. E.g.:

```dart
print("State before play: ${player.playbackState}");
```

**Comment by o4x** [comment]
I'm sorry bro. The problem was my code.Thank you for your time and good plugins❤
