### ISSUE TITLE
Issue in some devices like Xiaomi A3, caused by Exoplayer

### ISSUE THREAD

**Issue by bal3m** [ryanheise/just_audio#73]
I got this error message from my debug:
```
E/ExoPlayerImplInternal(32501): Source error.
E/ExoPlayerImplInternal(32501): com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 401
E/ExoPlayerImplInternal(32501): 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:300)
E/ExoPlayerImplInternal(32501): 	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:177)
E/ExoPlayerImplInternal(32501): 	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
E/ExoPlayerImplInternal(32501): 	at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:961)
E/ExoPlayerImplInternal(32501): 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
E/ExoPlayerImplInternal(32501): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal(32501): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal(32501): 	at java.lang.Thread.run(Thread.java:764)
=================================================
```
Notice: The codec is mpeg

**Comment by stonega** [comment]
Can you put the audio link here? Looks like network error.

**Comment by bal3m** [comment]
http://shaincast.caster.fm:37625/listen.mp3?authncb6dcc7e6acbb8813de17eab2806d4d8
This is the url.

**Comment by stonega** [comment]
The link need to login, I don't think just audio can deal with it.

**Comment by bal3m** [comment]
I edited it, now it's work with the same problem.

**Comment by ryanheise** [comment]
Closing, but please open a new issue if you still encounter the problem with the latest release of just_audio and with a valid mp3 link. Note that in the latest version you can pass headers in the request.
