### ISSUE TITLE
Just Audio Error on await _player.setAudioSource(_playlist);

### ISSUE THREAD

**Issue by deep1931** [ryanheise/just_audio#837]
**Which API doesn't behave as documented, and how does it misbehave?**
await _player.setAudioSource(_playlist);

**Minimal reproduction project**
Provide a link here using one of two options:
Not have any test app, because I happened with my running project

**To Reproduce (i.e. user steps, not code)**
Restart the app, if you are set audio source on load of app, then it will happen on app load other wise on event which is triggering the `await _player.setAudioSource(_playlist);` . 
If we comment this line, then everything works, except player functionality, otherwise app crashed. 

**Error messages**

```
E/AndroidRuntime(29193): FATAL EXCEPTION: main
E/AndroidRuntime(29193): Process: com.myapp.myapp, PID: 29193
E/AndroidRuntime(29193): java.lang.NoSuchMethodError: No virtual method buildOrThrow()Lcom/google/common/collect/ImmutableMap; in class Lcom/google/common/collect/ImmutableMap$Builder; or its super classes (declaration of 'com.google.common.collect.ImmutableMap$Builder' appears in /data/app/~~w8o-YhL68Tea9ikpfdER9g==/com.myapp.myapp-Tng-aVz190Pc8uM2piHH8g==/base.apk!classes21.dex)
E/AndroidRuntime(29193):        at com.google.android.exoplayer2.audio.AudioCapabilities.<clinit>(AudioCapabilities.java:75)
E/AndroidRuntime(29193):        at com.google.android.exoplayer2.audio.DefaultAudioSink$Builder.<init>(DefaultAudioSink.java:267)
E/AndroidRuntime(29193):        at com.google.android.exoplayer2.DefaultRenderersFactory.buildAudioSink(DefaultRenderersFactory.java:615)
E/AndroidRuntime(29193):        at com.google.android.exoplayer2.DefaultRenderersFactory.createRenderers(DefaultRenderersFactory.java:294)
E/AndroidRuntime(29193):        at com.google.android.exoplayer2.ExoPlayerImpl.<init>(ExoPlayerImpl.java:240)
E/AndroidRuntime(29193):        at com.google.android.exoplayer2.ExoPlayer$Builder.build(ExoPlayer.java:1053)
E/AndroidRuntime(29193):        at com.ryanheise.just_audio.AudioPlayer.ensurePlayerInitialized(AudioPlayer.java:736)
E/AndroidRuntime(29193):        at com.ryanheise.just_audio.AudioPlayer.onMethodCall(AudioPlayer.java:410)
E/AndroidRuntime(29193):        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/AndroidRuntime(29193):        at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/AndroidRuntime(29193):        at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/AndroidRuntime(29193):        at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/AndroidRuntime(29193):        at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(29193):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(29193):        at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(29193):        at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(29193):        at android.app.ActivityThread.main(ActivityThread.java:8751)
E/AndroidRuntime(29193):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(29193):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/AndroidRuntime(29193):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
I/Process (29193): Sending signal. PID: 29193 SIG: 9
Lost connection to device.

```

**Expected behavior**
It should load the playlist, as it was working some time ago, at sudden it stopped working

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: macOS Monterey v12.6
 
**Smartphone (please complete the following information):**
 - Device: Samsung s21, Mi note 7 pro
 - OS: Android 12 and Android 10

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.6 21G115 darwin-arm, locale en-CA)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.71.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

```

**Additional context**
NA

**Comment by ryanheise** [comment]
> **Minimal reproduction project**
> Provide a link here using one of two options:
> Not have any test app, because I happened with my running project

I will really need a means to reproduce this. I know it's hard, but consider that is still the easy job compared to the person who has to fix the bug. That is impossible to do if I have no way to reproduce it and test if my fix is working.

**Comment by deep1931** [comment]
Yes I understand too, while writing this line I was not happy, so i will upload test example asap.

Thanks.

**Comment by deep1931** [comment]
Hello,
I had made an test project but in test project same method is working fine, but still have issue in existing project. May be some libs are clashing with other, or something like this. So I think it is difficult to reproduce till I don't find the exact issue. 

Going to close the issue because of untraceable issue.
