### ISSUE TITLE
Unhandled Exception: PathAccessException: Cannot rename  (OS Error: Another program is using this file, and the process cannot access it.".

### ISSUE THREAD

**Issue by au-top** [ryanheise/just_audio#959]
**Which API doesn't behave as documented, and how does it misbehave?**

I think this is related to 'LockCachingAudioSource' and the file type 'wav' 'acc' because when I use`“ https://s3.amazonaws.com/scifri-episodes/scifri20181123-episode.mp3 "` This problem did not arise

call ` _player.setAudioSource(LockCachingAudioSource(Uri.parse("https://dl.espressif.com/dl/audio/ff-16b-2c-44100hz.aac")));` or ` _player.setAudioSource(LockCachingAudioSource(Uri.parse("https://dl.espressif.com/dl/audio/ff-16b-2c-44100hz.wav")));`
` Unhandled Exception: PathAccessException: Cannot rename file to `

throw error 

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PathAccessException: Cannot rename file to 'C:\Users\autop\AppData\Local\Temp\just_audio_cache\remote\76ef3491cf13296154930fa29a7a8cab58a45eb5a842e87e47528cae6da4161a.aac', path = 'C:\Users\autop\AppData\Local\Temp\just_audio_cache\remote\76ef3491cf13296154930fa29a7a8cab58a45eb5a842e87e47528cae6da4161a.aac.part' (OS Error: 另一个程序正在使用此文件，进程无法访问。
, errno = 32)
#0      _File.throwIfError (dart:io/file_impl.dart:675:7)
#1      _File.renameSync (dart:io/file_impl.dart:349:5)
#2      LockCachingAudioSource._fetch.<anonymous closure>
just_audio.dart:2974
<asynchronous suspension>

```

**Minimal reproduction project**
Provide a link here using one of two options:
```dart
// This is a minimal example demonstrating a play/pause button and a seek bar.
// More advanced examples demonstrating other features can be found in the same
// directory as this example in the GitHub repository.

import 'package:audio_session/audio_session.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:just_audio/just_audio.dart';
import 'package:just_audio_example/common.dart';
import 'package:rxdart/rxdart.dart';

void main() => runApp(const MyApp());

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  MyAppState createState() => MyAppState();
}

class MyAppState extends State<MyApp> with WidgetsBindingObserver {
  final _player = AudioPlayer();

  @override
  void initState() {
    super.initState();
    ambiguate(WidgetsBinding.instance)!.addObserver(this);
    SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
      statusBarColor: Colors.black,
    ));
    _init();
  }

  Future<void> _init() async {
    // Inform the operating system of our app's audio attributes etc.
    // We pick a reasonable default for an app that plays speech.
    final session = await AudioSession.instance;
    await session.configure(const AudioSessionConfiguration.speech());
    // Listen to errors during playback.
    _player.playbackEventStream.listen((event) {}, onError: (Object e, StackTrace stackTrace) {
      print('A stream error occurred: $e');
    });
    // Try to load audio from a source and catch any errors.
    try {
      // AAC example: https://dl.espressif.com/dl/audio/ff-16b-2c-44100hz.aac
      await _player.setAudioSource(LockCachingAudioSource(Uri.parse("https://dl.espressif.com/dl/audio/ff-16b-2c-44100hz.aac")));
    } catch (e) {
      print("Error loading audio source: $e");
    }
  }

  @override
  void dispose() {
    ambiguate(WidgetsBinding.instance)!.removeObserver(this);
    // Release decoders and buffers back to the operating system making them
    // available for other apps to use.
    _player.dispose();
    super.dispose();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.paused) {
      // Release the player's resources when not in use. We use "stop" so that
      // if the app resumes later, it will still remember what position to
      // resume from.
      _player.stop();
    }
  }

  /// Collects the data useful for displaying in a seek bar, using a handy
  /// feature of rx_dart to combine the 3 streams of interest into one.
  Stream<PositionData> get _positionDataStream => Rx.combineLatest3<Duration, Duration, Duration?, PositionData>(_player.positionStream, _player.bufferedPositionStream,
      _player.durationStream, (position, bufferedPosition, duration) => PositionData(position, bufferedPosition, duration ?? Duration.zero));

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: SafeArea(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.center,
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              // Display play/pause button and volume/speed sliders.
              ControlButtons(_player),
              // Display seek bar. Using StreamBuilder, this widget rebuilds
              // each time the position, buffered position or duration changes.
              StreamBuilder<PositionData>(
                stream: _positionDataStream,
                builder: (context, snapshot) {
                  final positionData = snapshot.data;
                  return SeekBar(
                    duration: positionData?.duration ?? Duration.zero,
                    position: positionData?.position ?? Duration.zero,
                    bufferedPosition: positionData?.bufferedPosition ?? Duration.zero,
                    onChangeEnd: _player.seek,
                  );
                },
              ),
            ],
          ),
        ),
      ),
    );
  }
}

/// Displays the play/pause button and volume/speed sliders.
class ControlButtons extends StatelessWidget {
  final AudioPlayer player;

  const ControlButtons(this.player, {Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Row(
      mainAxisSize: MainAxisSize.min,
      children: [
        // Opens volume slider dialog
        IconButton(
          icon: const Icon(Icons.volume_up),
          onPressed: () {
            showSliderDialog(
              context: context,
              title: "Adjust volume",
              divisions: 10,
              min: 0.0,
              max: 1.0,
              value: player.volume,
              stream: player.volumeStream,
              onChanged: player.setVolume,
            );
          },
        ),

        /// This StreamBuilder rebuilds whenever the player state changes, which
        /// includes the playing/paused state and also the
        /// loading/buffering/ready state. Depending on the state we show the
        /// appropriate button or loading indicator.
        StreamBuilder<PlayerState>(
          stream: player.playerStateStream,
          builder: (context, snapshot) {
            final playerState = snapshot.data;
            final processingState = playerState?.processingState;
            final playing = playerState?.playing;
            if (processingState == ProcessingState.loading || processingState == ProcessingState.buffering) {
              return Container(
                margin: const EdgeInsets.all(8.0),
                width: 64.0,
                height: 64.0,
                child: const CircularProgressIndicator(),
              );
            } else if (playing != true) {
              return IconButton(
                icon: const Icon(Icons.play_arrow),
                iconSize: 64.0,
                onPressed: player.play,
              );
            } else if (processingState != ProcessingState.completed) {
              return IconButton(
                icon: const Icon(Icons.pause),
                iconSize: 64.0,
                onPressed: player.pause,
              );
            } else {
              return IconButton(
                icon: const Icon(Icons.replay),
                iconSize: 64.0,
                onPressed: () => player.seek(Duration.zero),
              );
            }
          },
        ),
        // Opens speed slider dialog
        StreamBuilder<double>(
          stream: player.speedStream,
          builder: (context, snapshot) => IconButton(
            icon: Text("${snapshot.data?.toStringAsFixed(1)}x", style: const TextStyle(fontWeight: FontWeight.bold)),
            onPressed: () {
              showSliderDialog(
                context: context,
                title: "Adjust speed",
                divisions: 10,
                min: 0.5,
                max: 1.5,
                value: player.speed,
                stream: player.speedStream,
                onChanged: player.setSpeed,
              );
            },
          ),
        ),
      ],
    );
  }
}

```
**To Reproduce (i.e. user steps, not code)**
1. Run Code 

**Error messages**

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PathAccessException: Cannot rename file to 'C:\Users\autop\AppData\Local\Temp\just_ audio_ cache\remote\76ef3491cf13296154930fa29a7a8cab58a45eb5a842e87e47528cae6da4161a.aac', path = 'C:\Users\autop\AppData\Local\Temp\just_ audio_ "Cache remote 76ef3491cf13296154930fa29a7a8cab58a45eb5a842e87e47528cae6da4161a. aac. part '(OS Error: Another program is using this file, and the process cannot access it.".
```

raw

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PathAccessException: Cannot rename file to 'C:\Users\autop\AppData\Local\Temp\just_audio_cache\remote\76ef3491cf13296154930fa29a7a8cab58a45eb5a842e87e47528cae6da4161a.aac', path = 'C:\Users\autop\AppData\Local\Temp\just_audio_cache\remote\76ef3491cf13296154930fa29a7a8cab58a45eb5a842e87e47528cae6da4161a.aac.part' (OS Error: 另一个程序正在使用此文件，进程无法访问。
```

**Expected behavior**
play audio

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows11
 - Browser -

**Smartphone (please complete the following information):**
 - Device: -
 - OS: -

**Flutter SDK version**
```
Flutter 3.8.0-12.0.pre.15 • channel master • https://github.com/flutter/flutter.git
Framework • revision 0db47bdd07 (6 weeks ago) • 2023-02-11 03:44:56 -0800
Engine • revision d8e01097e6
Tools • Dart 3.0.0 (build 3.0.0-229.0.dev) • DevTools 2.21.1
```

**Additional context**

**Comment by ryanheise** [comment]
I wouldn't expect the error to be specific to the filename extension because the logic is the same, but just as a sanity check, can you close all other programs and perhaps better, reboot the computer, and then run the app directly without any other programs running?

**Comment by devyueyue** [comment]
Hi，How to play music in the background and compatible with the playback completion status. When the audio playback app is switched to the background, the playback progress stops refreshing

**Comment by devyueyue** [comment]
How to monitor the playback completion status when playing music in the background (it is necessary to monitor the playback completion status and upload data to the server). When the audio playback app is switched to the background, the playback progress stops refreshing
